### ISSUE TITLE
Tarball download error

### ISSUE THREAD

**Issue by masyed** [aws/aws-codedeploy-agent#10]
Hello Guys,
Just setup the codedeploy, and triggered the deploy via Github.

I completed all the pre-requisite steps. I make a new commit to the repo and i can see new deployment being triggered in CodeDeploy console under deployments.

It always fails at "DownloadBundle" stage. The error message is this:

Could not download bundle at 'https://api.github.com/repos/my_org_name/my_repo_name/tarball/commit_id' after 3 retries. Server returned codes: 404 'Not Found'; 404 'Not Found'; 404 'Not Found'; 404 'Not Found'.

Looks like the URL that the agent creates for downloading the tarball of the comitt does not exist. I tried the same URL directly in browser and i still get 404 error.

But it does work, if I change the URL to this format:

https://github.com/my_org_name/my_repo_name/tarball/commit_id

Any help will be appreciated, as i can not find anything regarding this under CodeDeploy manual.

**Comment by masyed** [comment]
going to resubmit new issue with more precise info,

**Comment by louisallen** [comment]
Having the same issue right now, what was the fix?

**Comment by heijmerikx** [comment]
I have not tested it twice, but it seems to be related by forgetting to 'push' your commit. I had the exact same problem.

I did a commit, then checked the latest hash by doing a 'git log' and executed the deployment using the hash in the aws cli. And got the 404's in the Code deploy interface. Pushing the commit and executing the same cli command to deploy again resolved the issue for me.

**Comment by daljeet-singh** [comment]
Hi, i am also facing this issue, any fix?

**Comment by louisallen** [comment]
Try logging into github first within aws codedeploy for your development application (connect to github).

**Comment by daljeet-singh** [comment]
Hi,
I tried this also but it fails. I checked logs  and it seems that
API.github blocks the request while downloading tar

**Comment by NiveditJain** [comment]
Facing the same issue, none of the above-mentioned solutions worked!

**Comment by netengineersam** [comment]
Facing the same issue too

**Comment by netengineersam** [comment]
check out this link to see if it might be helpful
https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-your-membership-in-organizations/requesting-organization-approval-for-oauth-apps#requesting-organization-approval-for-an-oauth-app-youve-already-authorized-for-your-personal-account

**Comment by SuyogShinde942** [comment]
maybe commit was not proper, so try again to commit and use a new commit id
