### ISSUE TITLE
Support a Byte Order Mark At the Beginning of the appspec.yml File

### ISSUE THREAD

**Issue by bgshacklett** [aws/aws-codedeploy-agent#100]
Currently, when an appspec.yml file is saved with a Byte Order Mark at the beginning of the file, deployments will fail with the following error:
    "The deployment failed because an invalid version value () was entered in the application specification file. Make sure your AppSpec file specifies "0.0" as the version, and then try again."

While Byte Order Marks are not recommended for UTF-8, the Unicode specification does state that they may be encountered in some cases, and it would save some difficulty, especially for Windows users, if this was supported in the CodeDeploy agent.

**Comment by gdeblina** [comment]
Thank you for reporting this issue. We have added an item to update the agent to support UTF-8 character set to fix this issue. We will try to prioritize the fix.

**Comment by mwjones-aws** [comment]
Closed, no plan to prioritize. See the `-Encoding` param in [these docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-file?view=powershell-7.2&viewFallbackFrom=powershell-6#parameters). The default encoding is `utf8NoBOM` starting with PowerShell 6.0.
