### ISSUE TITLE
No such file or directory @ rb_sysopen - /opt/codedeploy-agent/deployment-root/b2316ed2-5e96-4514-bb4b-c7f20534ceef/d-PZYU2HUMK/deployment-archive/appspec.yml

### ISSUE THREAD

**Issue by suhailgupta03** [aws/aws-codedeploy-agent#102]
While I am trying to deploy an application from an external bucket (shared by some user), I get an error that says:
`No such file or directory @ rb_sysopen - /opt/codedeploy-agent/deployment-root/b2316ed2-5e96-4514-bb4b-c7f20534ceef/d-PZYU2HUMK/deployment-archive/appspec.yml`

The error code is shown as `Unknown error` in the logs.

I have my `appspec.yml` in place i.e root of the package. I tried to remove the previous deployment details from `/opt/codedeploy-agent/deployment-root` but that didn't help. What could be the case here?

**Comment by LegNeato** [comment]
I think I've seen this when the zipfile can't be extracted.... does the file `/opt/codedeploy-agent/deployment-root/b2316ed2-5e96-4514-bb4b-c7f20534ceef/d-PZYU2HUMK/bundle.tar have zero bytes?

Does `unzip /opt/codedeploy-agent/deployment-root/b2316ed2-5e96-4514-bb4b-c7f20534ceef/d-PZYU2HUMK/bundle.tar -d /tmp; echo $?;` show 1?

Just put up https://github.com/aws/aws-codedeploy-agent/pull/104 which might help.

**Comment by normoes** [comment]
I had exactly the same error when "cleaning" the `/opt/codedeploy-agent/deployment-root/` directory, in order to get some more free space again.

Obviously, that is not a good idea.

Now every deployment fails...

**Comment by normoes** [comment]
This [stackoverflow](https://stackoverflow.com/questions/27923991/amazon-web-service-codedeploy-appspec-yml-problems) thread helped me to get a step further again.

**Comment by victorbadila** [comment]
+1, I "cleaned" the folder as well. something fishy in how the aws codedeploy agent "thinks"

**Comment by letsspeak** [comment]
In my case, when Travis-CI's CodeDeploy IAM didn't incluede S3 Access policy, this error occured.

**Comment by rohkat-aws** [comment]
@suhailgupta03 if this is resolved. Can i close this

**Comment by Ashoks22** [comment]
I am getting error as mentioned.No such file or directory - /opt/codedeploy-agent/deployment-root/4923a8e2-0408-40a8-a997-9714196166df/d-6F2OWUZ9J/deployment-archive/home/ec2-user/inoutserver/dist

**Comment by Ashoks22** [comment]
Hi, I am getting error as 
**No such file or directory - /opt/codedeploy-agent/deployment-root/4923a8e2-0408-40a8-a997-9714196166df/d-6F2OWUZ9J/deployment-archive/home/ec2-user/inoutserver/dist** in the Install event. 
Please suggest how to fix the issue.

**Comment by mohanm911** [comment]
Somthing wrong in your Execute shell scrpit
