### ISSUE TITLE
debian package does not honor /usr/sbin/policy-rc.d in post install script

### ISSUE THREAD

**Issue by mercora** [aws/aws-codedeploy-agent#107]
After installing the codedeploy-agent package with dpkg the daemon is automatically started and enabled  in the post install script. While this is common on debian based systems, normally it is possible to prevent the startup using "/usr/sbin/policy-rc.d" but this is currently not honored by the codedeploy-agent package.

This can be really annoying when preparing system images in a chroot. As an alternative to implementing the policy-rc.d i would be happy if the package would support systemd. systemd automatically detects that it is running in a chroot and wont start anything. It also has its own mechanisms to "mask" a service to prevent it from startup.

**Comment by asaf-erlich** [comment]
Hello Patrick,

This solution is very specific to dpkg. I think the right feature we need to work on is to allow a way to install the agent without starting it up, maybe with a flag you pass into the install command. That way it works on all systems no matter which package manager is used (we vend the agent with .deb, .rpm, and for windows an msi). It's a feature we need to prioritize. I will bring it up to the team that more customers are asking for this. Thanks for the feedback.

-Asaf
