### ISSUE TITLE
Github deployment: DownloadBundle Unknown Issues

### ISSUE THREAD

**Issue by jonathan-bird** [aws/aws-codedeploy-agent#112]
I've been getting 3 unknown errors on DownloadBundle all of a sudden in the last week or so. 

One: Error extracting tar archive: 2
Two: End of file reached
Three: No such file or directory - getcwd

I use Github deployment through the portal and I've never had an issue before. Any ideas? What info do you need me to provide?

**Comment by jonathan-bird** [comment]
Update: seems to be happening as it downloads the bundle.tar which has size of 0.

Does add a huge file into /tmp folder though which starts with open-uri2017....

$ tar -zxvf bundle.tar 

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

$ ll
total 0
-rw-r--r-- 1 root root 0 May 24 04:36 bundle.tar

**Comment by asaf-erlich** [comment]
This is an odd error. Nothing has changed in the last few days on our end. Any way you can provide a way for us to reproduce this error? Is your github repo private or can we try to do a deployment and see the error ourselves? Can you also try downloading a tar / zip directly from github and verify the file contents are valid?

https://stackoverflow.com/questions/2751227/how-to-download-source-in-zip-format-from-github

**Comment by jonathan-bird** [comment]
I manually DL'd it and it untars without any issues. Even on the server. Also have other deployments on the server working perfectly.

Unfortunately it's a private repo but I'm fairly certain there's something else at play here.

**Comment by asaf-erlich** [comment]
It sounds like we go to download it and something fails on the download step... but we don't properly stop and exist there and instead keep going leading to a failure to extract a file which has size 0.

**Comment by asaf-erlich** [comment]
Oh, what host OS are you using?

**Comment by asaf-erlich** [comment]
And what ruby version, just in case.

**Comment by webratz** [comment]
I'm seeing that issue also, but I'm using s3 for the deployment bundle and tar.gz as format.
Download of the bundle via aws cli on the affected instance works fine.

Error message shown `No such file or directory - getcwd`
Amazon Linux 2017.03
codedeploy-agent.noarch                1.0-1.1106

**Comment by iramello** [comment]
Got the same issue, Ubuntu 16.04, agent 1.0-1.1231, solved by restarting the agents in the servers.

**Comment by jonathan-bird** [comment]
Turned out my issue was actually HDD limit on the server where it wasn't saving the bundle but wasn't erroring, then tried to extract and gave this error.

**Comment by soukicz** [comment]
Same issue with error "No such file or directory - getcwd" on amzn-ami-2017.09.b-amazon-ecs-optimized and only on some instances - fixed after restarting codedeploy-agent

**Comment by dleblanc-vidcruiter** [comment]
We're seeing this issue occur on new instances deployed with Auto-scaling causing the scaling request to fail. It does not happen in all cases but there appears to be a couple of AMIs that are more prone to this than others. What's more interesting is that we have logged occurrences of these same problematic AMIs successfully launching leading us to believe that the saved state of the AMI can't possibly be in an entirely "bad state" since some (small) percentage of the attempts on this AMI are successful. As a part of troubleshooting this I'm going to attempt to create a new AMI for one of the failing Auto Scaling Groups and if I find a particular action that seems to remedy the failed AMI I'll report it here.

**Comment by grishaandrianov** [comment]
I have been getting one of the described errors: No such file or directory.
Most of the times my deployment works fine, but 1 of 2-4 times I am getting this error.
The only error I have found in logs:

```
2018-01-08 06:40:57 ERROR [codedeploy-agent(4860)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Error during perform: Errno::ENOENT - No such file or directory - C:/Sites/AAAA/bin/BBBB.dll - C:/Windows/TEMP/ocr597C.tmp/lib/ruby/2.0.0/fileutils.rb:1381:in `initialize'
C:/Windows/TEMP/ocr597C.tmp/lib/ruby/2.0.0/fileutils.rb:1381:in `open'
C:/Windows/TEMP/ocr597C.tmp/lib/ruby/2.0.0/fileutils.rb:1381:in `block in copy_file'
C:/Windows/TEMP/ocr597C.tmp/lib/ruby/2.0.0/fileutils.rb:1380:in `open'
C:/Windows/TEMP/ocr597C.tmp/lib/ruby/2.0.0/fileutils.rb:1380:in `copy_file'
C:/Windows/TEMP/ocr597C.tmp/lib/ruby/2.0.0/fileutils.rb:477:in `copy_file'
C:/Windows/TEMP/ocr597C.tmp/lib/ruby/2.0.0/fileutils.rb:394:in `block in cp'
C:/Windows/TEMP/ocr597C.tmp/lib/ruby/2.0.0/fileutils.rb:1558:in `block in fu_each_src_dest'
C:/Windows/TEMP/ocr597C.tmp/lib/ruby/2.0.0/fileutils.rb:1574:in `fu_each_src_dest0'
C:/Windows/TEMP/ocr597C.tmp/lib/ruby/2.0.0/fileutils.rb:1556:in `fu_each_src_dest'
C:/Windows/TEMP/ocr597C.tmp/lib/ruby/2.0.0/fileutils.rb:393:in `cp'
C:/Windows/TEMP/ocr597C.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/install_instruction.rb:237:in `execute'
C:/Windows/TEMP/ocr597C.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/installer.rb:47:in `block (2 levels) in install'
C:/Windows/TEMP/ocr597C.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/installer.rb:46:in `each'
C:/Windows/TEMP/ocr597C.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/installer.rb:46:in `block in install'
C:/Windows/TEMP/ocr597C.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/installer.rb:45:in `open'
C:/Windows/TEMP/ocr597C.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/installer.rb:45:in `install'
C:/Windows/TEMP/ocr597C.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:120:in `block in <class:CommandExecutor>'
C:/Windows/TEMP/ocr597C.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:62:in `execute_command'
C:/Windows/TEMP/ocr597C.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:132:in `process_command'
C:/Windows/TEMP/ocr597C.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:65:in `perform'
C:/Windows/TEMP/ocr597C.tmp/src/opt/codedeploy-agent/lib/instance_agent/agent/base.rb:28:in `run'
C:/Windows/TEMP/ocr597C.tmp/src/opt/codedeploy-agent/bin/winagent.rb:43:in `block (2 levels) in service_main'
C:/Windows/TEMP/ocr597C.tmp/src/opt/codedeploy-agent/bin/winagent.rb:41:in `synchronize'
C:/Windows/TEMP/ocr597C.tmp/src/opt/codedeploy-agent/bin/winagent.rb:41:in `block in service_main'
C:/Windows/TEMP/ocr597C.tmp/src/opt/codedeploy-agent/bin/winagent.rb:88:in `with_error_handling'
C:/Windows/TEMP/ocr597C.tmp/src/opt/codedeploy-agent/bin/winagent.rb:38:in `service_main'
C:/Windows/TEMP/ocr597C.tmp/gemhome/gems/win32-service-0.8.7/lib/win32/daemon.rb:319:in `mainloop'
C:/Windows/TEMP/ocr597C.tmp/gemhome/gems/win32-service-0.8.7/lib/win32/daemon.rb:217:in `mainloop'
C:/Windows/TEMP/ocr597C.tmp/src/opt/codedeploy-agent/bin/winagent.rb:103:in `<main>'
```

I am certainly sure that there always was file C:/Sites/AAAAA/bin/BBBBB.dll in its place and in every zip-bundle too.

**Comment by asaf-erlich** [comment]
One thing to clarify is that we utilize (for linux anyway) shelling out to /bin/tar for tar and tgz formats. We don't do this for zip: https://github.com/aws/aws-codedeploy-agent/blob/27d5b31c72c5004e5683ee1fab1e51d65def75d6/lib/instance_agent/platform/linux_util.rb#L55

This implies to me that the problem is that tar is really telling us the file is not there. I'm pretty confident on-box gnu-tar doesn't have any bugs in it where this is concerned - if it says the file is not there it's probably not there for some reason. But one theory is that maybe even though the error says it's the tar reporting that error it might actually be that we're failing on the download step for some reason and silently proceeding. The fact that agent restarts are fixing it for you guys might lend credence to that theory. If you see this other github issue we're working on a fix that may help solve this problem as well (memory bloats up over time as s3 downloads): https://github.com/aws/aws-codedeploy-agent/issues/32

**Comment by dnorenavega-EDR** [comment]
Restart the code deploy agent did the trick for me, thank you @soukicz

**Comment by greendrake** [comment]
`sudo service codedeploy-agent restart` on the instance did the trick for me too.
But the issue still is: what causes this and how to prevent?

**Comment by sebastianreloaded** [comment]
i have a cronjob restarting the agent every night

**Comment by mahkali** [comment]
I've run into a similar issue: 

> No such file or directory - getcwd 

This occurred after the disk was full - codedeploy keeps five tar files which filled up the instance. After cleaning up and making space this issue started. Running `sudo service codedeploy-agent restart` solved the problem.

**Comment by estebanz01** [comment]
I'm seeing this behaviour from time to time in some deployment process we have setup for QA purposes, where we deploy a tgz file that is stored on S3. I've seen this happening on servers with plenty of space. Here's the trace that appears on the codedeploy log

```txt
ERROR [codedeploy-agent(1483)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Error during perform: Errno::ENOENT - No such file or directory - getcwd
 - /usr/lib/ruby/2.6.0/fileutils.rb:107:in `pwd'
/usr/lib/ruby/2.6.0/fileutils.rb:107:in `pwd'
/opt/codedeploy-agent/lib/instance_agent/platform/linux_util.rb:64:in `extract_tgz'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:384:in `unpack_bundle'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:115:in `block in <class:CommandExecutor>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:70:in `execute_command'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:115:in `process_command'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:97:in `acknowledge_and_process_command'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:76:in `block in perform'
/opt/codedeploy-agent/vendor/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/opt/codedeploy-agent/vendor/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/opt/codedeploy-agent/vendor/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/opt/codedeploy-agent/vendor/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/opt/codedeploy-agent/vendor/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/opt/codedeploy-agent/vendor/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
/opt/codedeploy-agent/vendor/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
WARN  [codedeploy-agent(1483)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Calling PutHostCommandComplete: "Code Error" 
INFO [codedeploy-agent(1483)]: Version file found in /opt/codedeploy-agent/.version with agent version OFFICIAL_1.2.0-1866_deb.
```

**Comment by t0shiii** [comment]
For anyone who is still experiencing the `No such file or directory - getcwd` issue not related to disk space availability, can you provide some more information?

```
Ruby Version:
Agent Version:
Operating System:
Disk Space Availability (% utilized):
```

**Comment by mwjones-aws** [comment]
Please reopen if you're still experiencing this issue using the [latest version of CodeDeploy Agent](https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent.html#codedeploy-agent-version-history)
