### ISSUE TITLE
Agent leaks sockets to AWS S3

### ISSUE THREAD

**Issue by cavaliercoder** [aws/aws-codedeploy-agent#115]
Occasionally, the CodeDeploy Agent leaks a socket when connecting to S3 to download application bundles. This is evident via call to netstat:

```
$ netstat -tp4
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp       54      0 ip-172-21-67-210.:53248 s3-ap-southeast-2:https CLOSE_WAIT  4953/codedeploy-age
...
```

This happens on a number of our Centos 7.2.1511 x86_64 instances on AWS EC2. Package details:
```
$ rpm -qi codedeploy-agent
Name        : codedeploy-agent
Version     : 1.0
Release     : 1.1106
Architecture: noarch
Install Date: Wed 03 May 2017 04:30:06 AM AWST
Group       : Applications/System
Size        : 14612247
License     : Amazon.com Internal
Signature   : (none)
Source RPM  : codedeploy-agent-1.0-1.1106.src.rpm
Build Date  : Thu 13 Apr 2017 12:20:12 AM AWST
Build Host  : sds-tod-workers-2c-m4l-247fd253.us-west-2.amazon.com
Relocations : (not relocatable)
Vendor      : Amazon.com
Summary     : Provides the required files for CodeDeploy agent to run in EC2 instances
Description :
CodeDeploy instance agent is responsible for doing the actual work of deploying software
on an EC2 instance.
```

We had a similar issue in applications using the AWS SDK for Javascript (I understand this is written in Ruby). For reference, the issue was addressed, we think (please confirm) in v2.50.0.

**Comment by asaf-erlich** [comment]
Thanks for bringing this to our attention. We're using the ruby aws sdk for S3 so we're simply doing whatever that one does. Is v2.50.0 the version of the AWS SDK that you're referring to where this was fixed?

**Comment by cavaliercoder** [comment]
We understand a similar issue was resolved in the AWS SDK for _Javascript_ somewhere around v2.50.0. Perhaps this issue is addressed by the Ruby SDK team?

**Comment by RohitK09** [comment]
we are currently working on a fix for this issue.

**Comment by Seikho** [comment]
@RohitK09 Is there a related issue you can link to?

**Comment by annamataws** [comment]
Issue https://github.com/aws/aws-codedeploy-agent/issues/60 is about upgrading AWS SDK
Closing issue. Track the progress in #60
