### ISSUE TITLE
Working directory gets changed after trying to deploy bad artifact

### ISSUE THREAD

**Issue by nikhilo** [aws/aws-codedeploy-agent#116]
During iterations of codedeploy, I mistakenly uploaded a bad file as a tar.gz file.
For this deploy I got following error as expected:
```
2017-06-13 01:51:11 ERROR [codedeploy-agent(14067)]: InstanceAgent::LinuxUtil: Error extracting tar archive: 2
2017-06-13 01:51:11 INFO  [codedeploy-agent(14067)]: Version file found in /opt/codedeploy-agent/.version.
2017-06-13 01:51:11 INFO  [codedeploy-agent(14067)]: [Aws::CodeDeployCommand::Client 200 0.067077 0 retries] put_host_command_complete(command_status:"Failed",diagnostics:{format:"JSON",payload:"{\"error_code\":5
,\"script_name\":\"\",\"message\":\"Error extracting tar archive: 2\",\"log\":\"\"}"},host_command_identifier:"WyJjb20uYW1hem9uLmFwb2xsby5kZXBsb3ljb250cm9sLmRvbWFpbi5Ib3N0Q29tbWFuZElkZW50aWZpZXIiLHsiZGVwbG95bWVud
ElkIjoiQ29kZURlcGxveS91cy1lYXN0LTEvUHJvZC9hcm46YXdzOnNkczp1cy1lYXN0LTE6MDU3NDgwMjA1MDIyOmRlcGxveW1lbnQvZC1NNlJQU1FGWE0iLCJob3N0SWQiOiJhcm46YXdzOmVjMjp1cy1lYXN0LTE6MDU3NDgwMjA1MDIyOmluc3RhbmNlL2ktMGQ0OTgyMDI5ODFkZ
DBkMTMiLCJjb21tYW5kTmFtZSI6IkRvd25sb2FkQnVuZGxlIiwiY29tbWFuZFBvc2l0aW9uIjoyLCJjb21tYW5kQXR0ZW1wdCI6MX1d")

2017-06-13 01:51:11 ERROR [codedeploy-agent(14067)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Error during perform: RuntimeError - Error extracting tar archive: 2 - /opt/codedeploy-agent/lib/insta
nce_agent/platform/linux_util.rb:84:in `execute_tar_command'
```

But, subsequent deploys kept failing because I was using `${PWD}` in the start script which I had configured in appspec.
$PWD should have been`/opt/codedeploy/`
But, error logs were showing that $PWD was set to `/opt/codedeploy-agent/deployment-root/<DEPLOYMENT_GROUP>/<ID_OF_BAD_FILE_DEPLOY>/deployment-archive/`

I restarted codedeploy agent on one of the hosts, which now succeeds with the deploy. Other host still fails trying to look for files in,
`/opt/codedeploy-agent/deployment-root/<DEPLOYMENT_GROUP>/<ID_OF_BAD_FILE_DEPLOY>/deployment-archive/`
instead of,
`/opt/codedeploy/`

I think when extract operation fails, the agent does not reset the working directory to `/opt/codedeploy/`

**Comment by asaf-erlich** [comment]
Which Lifecycle Event specifically is it failing in? ApplicationStart? ApplicationStop? DownloadBundle? I ask because some operations (e.g. ApplicationStop) always use the previous revision. You can add a flag or check a box in the console to ignore application stop failures (flag is --ignore-application-stop-failures):

https://docs.aws.amazon.com/cli/latest/reference/deploy/create-deployment.html

**Comment by nikhilo** [comment]
I think it could be a bug in `DownloadBundle`. I'm not sure how to check that. Because a bad archive affects all next deployments by not reverting back `PWD` to `/opt/codedeploy`.

**Comment by feverLu** [comment]
Do you have an example of failed deploymentId and region that I can get for further investigation? Do you have any script/command in the bad archive to update the environment variable?

**Comment by nikhilo** [comment]
@feverLu I will create a forced failed deployment, and will provide you the Deployment ID soon.
Also, `PWD` environment variable is not being set anywhere in the deployment scripts.

**Comment by rohkat-aws** [comment]
@nikhilo were you able to to resolve this ?

**Comment by rohkat-aws** [comment]
@nikhilo since there has been no response closing this
