### ISSUE TITLE
CodeDeploy Local CLI is not packaged

### ISSUE THREAD

**Issue by veetow** [aws/aws-codedeploy-agent#117]
The `codedeploy-local` script and libs (`AWS::CodeDeploy::Local::*`) are not packaged in the artifacts in the codedeploy s3 bucket (e.g.: `s3://aws-codedeploy-us-east-1/latest/codedeploy-agent.noarch.rpm`).  Will they be in the near future?  Is there a documented set of installation steps somewhere?  Thanks!

**Comment by gorup** [comment]
We are working on launching the feature, it will be finished in the near future. We will update this issue when its out, thanks!

**Comment by veetow** [comment]
Glad to hear it.  I've tested it from `master` and it's working well.

**Comment by veetow** [comment]
Any updates on the launch timeline for this?

**Comment by RohitK09** [comment]
this issue was fixed during the last release of the agent and is in production

**Comment by asaf-erlich** [comment]
This was released in December.
