### ISSUE TITLE
AWS CodeDeploy DownloadBundle Event

### ISSUE THREAD

**Issue by mike-newman** [aws/aws-codedeploy-agent#120]
Using CodeDeploy for a couple months with no issues on our repos. After reseting the Head today on a development branch we not get the following error in CodeDeploy.  "No such file or directory - getcwd".  This error is verbose from the CodeDeploy status.  I have tried to deploy from previous commit ID deployments as well.

**Comment by mmerkes** [comment]
Weird. Does it specify what file or directory doesn't exist specifically? If it's not a lot of work, try spinning up a new EC2 instance and do a fresh deployment to that instance. I wonder if it's related to some improper clean up or something on the box.

**Comment by kundankmd** [comment]
Not sure if this helps but I had that issue when our repository had a dead symlink

**Comment by rohkat-aws** [comment]
@mike-newman can i close this issue if this is resolved.

**Comment by rohkat-aws** [comment]
@mike-newman @kundankmd closing this as there was no response

**Comment by fremail** [comment]
The issue still happens

**Comment by rubashanti** [comment]
same issue happened, could you please update us with the satus

**Comment by Helen1987** [comment]
Could you add more details? Previous vs current OS. Is it only for existing instances or old one as well?

**Comment by ryanmt** [comment]
I am also seeing this issue intermittently without other changes made to the system.

**Comment by rubashanti** [comment]
Os is linux

**Comment by rubashanti** [comment]
The CodeDeploy deployment fails during the "DownloadBundle" hook with:
InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Error during perform: Errno::ENOENT - No such file or directory - getcwd

Checking code deploy agent code, it failed when it is trying to get the working dir, and for some reason it's not finding it
===
working_dir = FileUtils.pwd()
===
https://github.com/aws/aws-codedeploy-agent/blob/27d5b31c72c5004e5683ee1fab1e51d65def75d6/lib/instance_agent/platform/linux_util.rb#L52

**Comment by Israphel** [comment]
We randomly have this issue in a particular project. The only difference I can say is that, in my case, it's an ASG that has two codepipelines + codedeploy pointing to it. Of course, different artifacts and different deploy scripts in each case.

But, codedeploy creates a subfolder with the deployment id, so they shouldn't collide.

Also my pipelines are multiregion and it never happened in both regions at once (even tho the machines are built the same and the artifact is the same)

**Comment by rubashanti** [comment]
I have opened the issue : https://github.com/aws/aws-codedeploy-agent/issues/244 for following up

**Comment by brblck** [comment]
relates to: https://github.com/aws/aws-codedeploy-agent/issues/255
