### ISSUE TITLE
Debian postinst script bypasses systemd service control

### ISSUE THREAD

**Issue by danielkza** [aws/aws-codedeploy-agent#131]
The postinst script contains the following line:

    service codedeploy-agent start-no-update

Since systemd does not support the custom command, it is bypassed and sent to the /etc/init.d script, which starts the agent manually. It can then no longer be controlled by systemd, and `service codedeploy-agent stop` does nothing because systemd believes the daemon is not running.

Looking at the script, it seems `start-no-update` does the same as `start`, so it should not be necessary to call it explicitly, which should fix the systemd situation.

**Comment by asaf-erlich** [comment]
This comment is a bit old at this point. Are you saying the fix is replace start-no-update with just start?

**Comment by asaf-erlich** [comment]
Also is this true of Ubuntu version >= 14.04? Or Is it only true >= 16.04?

**Comment by asaf-erlich** [comment]
Ok so start-no-update is custom and specific to our init.d script as you mentioned. What do you think is supposed to happen here (please educate me as I'm not an expert on deb files): https://github.com/aws/aws-codedeploy-agent/blob/master/init.d/codedeploy-agent#L85

**Comment by huribeir** [comment]
@asaf-erlich not a direct response to this, but in my opinion I think the best answer to this question is in the resolution of #130 . In short, make sure that install scripts correctly use SysV or systemd accordingly so there's no need to rely on systemd-sysv-generator.

**Comment by mwjones-aws** [comment]
Duplicated of #130
