### ISSUE TITLE
Deploying behaviour in an Auto scaling group

### ISSUE THREAD

**Issue by kundankmd** [aws/aws-codedeploy-agent#132]
This is more a question regarding the behaviour of Codedeploy agent deploying to the nodes in an ASG. We have started using AWS Codedeploy in production and after every deployment 

* We create an AMI which is running the latest deployment revision
* Create a new Launch Configuration (LC) using this AMI 
* Update the ASG to use this LC  

During an "up scale" event in ASG, I have noticed that AWS Codedeploy always takes almost the same time during "Download Bundle" and "Install" events even though the AMI has the latest version. 

Does the agent downloads and unzip the file from S3 every time even though the EC2 instance is running the latest deployment revision?

**Comment by tangerini** [comment]
Yes, the agent has no knowledge of what's in the AMI.
