### ISSUE TITLE
No such file or directory @ rb_sysopen - /opt/codedeploy-agent/deployment-root/9912fb35-1dbd-4059-ad23-9b0539932340/d-KVBZSCMFP/deployment-archive/adihealthdev/

### ISSUE THREAD

**Issue by satyakishores** [aws/aws-codedeploy-agent#138]
My deployment failed at the Install event stage. error code is 'Error CodeUnknownError'
No such file or directory @ rb_sysopen - /opt/codedeploy-agent/deployment-root/9912fb35-1dbd-4059-ad23-9b0539932340/d-KVBZSCMFP/deployment-archive/adihealthdev/

appspec.yml file is as below:
```os: linux
files:
  - source: /adihealthdev/
    destination: /var/www/adihealthdevupto271020172110
hooks:
  ApplicationStart:
    - location: /var/www/adihealthdevupto271020172110/scripts/start_server.sh
      timeout: 200
      runas: root
```

In start_server.sh I wrote
#!/bin/bash
sudo service apache2 restart

Please help.

**Comment by satyakishores** [comment]
I got the answer. I have changed the source in files to /

```files:
  - source: /
    destination: /var/www/adihealthdevupto271020172110```

Everything worked fine now.

**Comment by JohnVonNeumann** [comment]
Thanks for that @satyakishores
