### ISSUE TITLE
Code deploy not getting installed - Openssl issue

### ISSUE THREAD

**Issue by Jhonylouies** [aws/aws-codedeploy-agent#141]
Hi,

Im trying to install code-deploy agent in my server, but im getting an openssl issue. Can someone assist on this  issue.

The error im getting are as follows,

[root@my-server-2 src]# ./install auto
E, [2017-11-09T22:03:30.269329 #22554] ERROR -- : Unhandled exception: #<LoadError: cannot load such file -- openssl>
E, [2017-11-09T22:03:30.269420 #22554] ERROR -- :   at /usr/local/ruby2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
E, [2017-11-09T22:03:30.269451 #22554] ERROR -- :   at /usr/local/ruby2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
E, [2017-11-09T22:03:30.269474 #22554] ERROR -- :   at ./install:46:in `<main>'

And the openssl  version of my server is ,

[root@my-server-2 src]# rpm -qa | grep openssl
openssl-1.0.1e-57.el6.x86_64
openssl-static-1.0.1e-57.el6.x86_64
openssl098e-0.9.8e-20.el6.centos.1.x86_64
openssl-perl-1.0.1e-57.el6.x86_64
openssl-devel-1.0.1e-57.el6.x86_64

Any suggestions much appreciated.
-Jhony

**Comment by feverLu** [comment]
It seems the ruby version you are running(/usr/local/ruby2.2/lib/ruby/2.2.0) in your box is not compiled with openssl, but the install script requires openssl to be exist. If you have another version of the ruby installed, you can try with specifies ruby directory like "/usr/bin/ruby2.0 ./install --auto", or you can try solutions on this stackoverflow question: https://stackoverflow.com/questions/3464098/rails-3-no-such-file-to-load-openssl

**Comment by Jhonylouies** [comment]
@feverLu 

Great that works for me by installing on /usr/bin/ruby, But i have configured code-deploy for other servers with ruby2.2. Anyways Thanks for the help.!!!!!!!
