### ISSUE TITLE
releases in this repo are behind

### ISSUE THREAD

**Issue by lmj0011** [aws/aws-codedeploy-agent#155]
Wanted to know if this repo is a reliable source of finding out what's the lastest version of 
`codedeploy-agent`

It seems not. https://github.com/aws/aws-codedeploy-agent/releases

see: https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent.html#codedeploy-agent-supported-versions

**Comment by woodhull** [comment]
I just discovered this as well. It's super annoying.

**Comment by bchess** [comment]
+1, where can we find the source code of latest releases?

**Comment by rohkat-aws** [comment]
@lmj0011 @woodhull @bchess they are currently updated now.
