### ISSUE TITLE
Dependency Resolution For CodeDeploy Agent For DEB Failing When ruby is already Installed

### ISSUE THREAD

**Issue by rohkat-aws** [aws/aws-codedeploy-agent#157]
When Ruby is already installed and we run install Script for agent, the agent  fails on dependency resolution, the link has more details.
https://github.com/aws/aws-codedeploy-agent/issues/140

**Comment by mwjones-aws** [comment]
The latest version of CodeDeploy Agent, 1.3.2, supports Ruby 2.7.
