### ISSUE TITLE
sleep before running codedeploy agent

### ISSUE THREAD

**Issue by nbvehrfr** [aws/aws-codedeploy-agent#16]
Hello, 

In bin/install script there is a do_sanity_check('/sbin/service') call in when 'rpm' section (which is used on amazon linux). The problem is it actually waiting 3 min before running agent first time (when instance is created): sleep(3 * 60). What is the goal for this sleep (3 minutes!). Can we remove it?

Thanks
Tim

**Comment by suryanarayanan** [comment]
Hi Tim,

This has been removed in the latest released version of agent. We are in the process of updating the github repo.

Thanks,
Surya.

**Comment by suryanarayanan** [comment]
This has been fixed in the latest release. Please check https://github.com/aws/aws-codedeploy-agent/releases/tag/v1.0-1.751 Resolving.
