### ISSUE TITLE
Ubuntu install prompts if config files exist

### ISSUE THREAD

**Issue by james-portman** [aws/aws-codedeploy-agent#166]
If a config file exists for codedeploy, it seems impossible to have it install without prompting the user.

My use case is to place a custom config file before installing the agent.
I then want to install the agent and have it immediately use the custom config file.

I was attempting to place the config file after install, then restart the agent, but this can cause the server to be terminated if a codedeploy had begun before the service restart.

This would all not be an issue apart from the fact that this one and most Debian/Ubuntu packages start services immediately on install which is very unhelpful.

**Comment by rohkat-aws** [comment]
@james-portman thanks for pointing this out, we are looking into this and thanks for the pr too
