### ISSUE TITLE
Stopping CodeDeploy agent kills applications launched by CodeDeploy when using systemd

### ISSUE THREAD

**Issue by huribeir** [aws/aws-codedeploy-agent#169]
systemd uses the concept of [Control Groups](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/resource_management_guide/chap-introduction_to_control_groups) to group processes that are launched as part of a unit. Under certain situations, processes started by the CodeDeploy agent during a deployment can be associated to CodeDeploy's cgroup (i.e. if the process is not correctly daemonized). This creates a situation where, even though the parent launched process has its PPID set to 1 (in other words, not a child of codedeploy's agent process), it will be listed under codedeploy-agent unit cgroup. Here's an example:

```
# systemctl status codedeploy-agent.service
● codedeploy-agent.service - LSB: AWS CodeDeploy Host Agent
   Loaded: loaded (/etc/init.d/codedeploy-agent; bad; vendor preset: enabled)
   Active: active (running) since Tue 2018-06-05 23:12:41 AEST; 21min ago
   [...]
   CGroup: /system.slice/codedeploy-agent.service
           ├─29721 codedeploy-agent: master 29721
           ├─29729 codedeploy-agent: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller of master 2972
           ├─29738 /usr/sbin/httpd
           ├─29742 /usr/sbin/httpd
           ├─29743 /usr/sbin/httpd
           ├─29744 /usr/sbin/httpd
           ├─29745 /usr/sbin/httpd
           ├─29746 /usr/sbin/httpd
           ├─29747 /usr/sbin/httpd
           ├─29748 /usr/sbin/httpd
           └─29749 /usr/sbin/httpd

# ps xf -o pid,ppid,cmd  | awk ' BEGIN { getline; print } /codedeploy|httpd/ { print; } '
  PID  PPID CMD
29721     1 codedeploy-agent: master 29721
29729 29721  \_ codedeploy-agent: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller of master 29721
29738     1 /usr/sbin/httpd
29742 29738  \_ /usr/sbin/httpd
29743 29738  \_ /usr/sbin/httpd
29744 29738  \_ /usr/sbin/httpd
29745 29738  \_ /usr/sbin/httpd
29746 29738  \_ /usr/sbin/httpd
29747 29738  \_ /usr/sbin/httpd
29748 29738  \_ /usr/sbin/httpd
29749 29738  \_ /usr/sbin/httpd
```

The default systemd behavior when stopping a unit is to send a SIGTERM to all processes of the control group. On the above example, **stopping the CodeDeploy agent also stops all httpd processes**.

I am also submitting a PR that aims at fixing this issue by setting the [KillMode](https://www.freedesktop.org/software/systemd/man/systemd.kill.html#KillMode=) on CodeDeploy's standard unit file to 'process', which causes only the parent process to receive the SIGTERM.

**Comment by annamataws** [comment]
Added this to our backlog.

**Comment by takayukioda** [comment]
Can anyone share latest status for this issue?
I had same issue; I ran nodejs application using PM2, and pm2 gets killed when codedeploy-agent is been restarted.

I added code to restart codedeploy-agent when I had trouble using zip file, which is addressed in https://github.com/aws/aws-codedeploy-agent/issues/32, and [tried hacky solution](https://github.com/aws/aws-codedeploy-agent/issues/32#issuecomment-287872722) that tempoary solved memory leak issue.

**Comment by huribeir** [comment]
Hey,

the solution I proposed on the associated pull request #170 will prevent those processes from being killed (although it won't prevent them from being assigned to the same cgroup). Just add `KillMode=process` to the service's unit file.

Other than that, you may want to create a new systemd unit for your application and make it a "formal" service. That will result in systemd automatically creating a new cgroup for the service, thus isolating it from the CodeDeploy agent.

**Comment by mwjones-aws** [comment]
Closing as not planned. Please create a new systemd daemon for your application.

**Comment by philstrong** [comment]
You should not be starting the application purely from your script as it’s not resilient to restarts and obviously agent operations
