### ISSUE TITLE
Remove vendor/ from repo

### ISSUE THREAD

**Issue by jdrago999** [aws/aws-codedeploy-agent#17]
Add `vendor/` to `.gitignore`

**Comment by suryanarayanan** [comment]
Hi,

The vendor folder is required to run the tests. The main reason behind vending all our dependent gems is not to take dependency on RubyGems server. We also don't want our customers to be broken due to backwards incompatible changes to dependent gems.

Thanks,
Surya.

**Comment by suryanarayanan** [comment]
I've stripped the vendor folder to bare minimum now. It only contains two gems which are not publicly available and need to be vended. Resolving.
