### ISSUE TITLE
@reboot codedeploy-agent-update.sh --sanity-check starts the agent

### ISSUE THREAD

**Issue by ashemedai** [aws/aws-codedeploy-agent#171]
I was asked by Prakash Palanisamy (AWS) to create this issue here.

We run into a timing issue with CodeDeploy starting the agent before everything all our dependencies are properly started. This leads to our `/health/instance` check returning a 500, which causes CodeDeploy to return an unhealthy state to the ASG, lead to a lot of wasted EC2 instance starting and termination.

We build AMIs using Packer which contains everything except our in-house applications. We then use userdata to kick off puppet to finalise the box and its settings once it is running.

The CodeDeploy cron entries have a line `@reboot root /bin/sleep 45; /opt/codedeploy-agent/bin/update --sanity-check rpm`.

This points to this piece of code:
https://github.com/aws/aws-codedeploy-agent/blob/528b8f1b3c42140d76ef0bf0d747042f1eafb14c/bin/update#L385-L395

I am curious why the cron job wants to start the codedeploy-agent after (re)boot since there are already init.d and systemd unit services under `codedeploy-agent` and `codedeploy-agent.service`, respectively, which will start the agent at the appropriate time, keeping dependencies in mind.

**Comment by rohkat-aws** [comment]
@ashemedai quick question, cannot you just install the agent in the end, Other than that what you are suggesting is a valid concern and we will look into it.

**Comment by ashemedai** [comment]
@rohkat-aws We could, sure, although there seems to have been some initial miscommunication about best practices on this front when it first got implemented here where I work. Back then it was believed it was best to include it in the base AMI.

We prefer to have it pre-installed on the AMI to speed up instances and deployment and minimise the amount of additional package installing we need to do once the box boots up. We currently mainly use Puppet to fix up configuration files and so on.

But of course, fully open to best practices here. :)

**Comment by ashemedai** [comment]
To add to this, the reason why we went with the codedeploy-agent was because of this blurb in the AWS Best Practices about golden images: 

> Items that do not change often or that introduce external dependencies will typically be part of your golden image.

**Comment by rohkat-aws** [comment]
@ashemedai  and i totally agree with this, But incase of long pending fixes ,that you think might fix a bug, are also important to add in the Golden Image

**Comment by ashemedai** [comment]
Hi, given I filed this 3,5 years ago, does this still need to stay open or has it been fixed? Currently do not have a proper AWS environment to test this myself.

**Comment by mwjones-aws** [comment]
Closing this issue. We plan to remove the update script in an upcoming release. Please follow our recommended, supported approaches to update CodeDeploy agent on your fleet.

https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent-operations-update.html
