### ISSUE TITLE
Incompatible to any halfway modern ruby version

### ISSUE THREAD

**Issue by autarchprinceps** [aws/aws-codedeploy-agent#176]
The deb package says it has the following dependecy:
Dependency is not satisfiable: ruby2.0|ruby2.1|ruby2.2|ruby2.3

Even Ubuntu LTS installs ruby 2.5, but even 2.4 would not work with such a limitation, even though the surrounding installer claims 2.4 would be a supported version.

**Comment by f-breidenstein** [comment]
The missing 2.5 support already is discussed in #158 and there is a month-old open PullRequest (https://github.com/aws/aws-codedeploy-agent/pull/147) which "adds" the missing 2.5 support.

**Comment by rohkat-aws** [comment]
@autarchprinceps we are looking into this

**Comment by apenney** [comment]
I don't want to sound rude but just how long does it take to "look at this"?  CodeDeploy feels very unmaintained at times.  I guess we should complain directly through our TAM but I wish you'd take support of Ubuntu a little bit more seriously.  It's been -4- months since 18.04 was released.

**Comment by rohkat-aws** [comment]
@apenney we are looking at it, But there have been more pressing issues we are trying to work on. But rest assured we will be looking at this .

**Comment by autarchprinceps** [comment]
@rohkat-aws This isn't some random community project. We are paying for this through our AWS bills, which we definitively have, otherwise we wouldn't be interested in this. If you lack the manpower required, ask your superiors, AWS is more than successful enough to employ enough people.

**Comment by keithcyu** [comment]
CodeDeploy officially supports Ruby 2.5 and Ubuntu 18.04 through 1.0.1.1597 release. Closing this issue.
