### ISSUE TITLE
Environment variables not visible

### ISSUE THREAD

**Issue by andrzejtokarski** [aws/aws-codedeploy-agent#181]
I'm setting an environment variable using:
echo export APP_PORT=\"8080\" >> /etc/bashrc
from bash script in instance user_data. 

The variable is present when seen from interactive bash shell but is not available from scripts started with
hooks:
  ApplicationStart: ...

Is it an intended behavior?

**Comment by Constantin07** [comment]
@andrzejtokarski have you tried to specify the systemwide environment variable in a file here `/etc/profile.d/*.sh`  ?

**Comment by rohkat-aws** [comment]
@andrzejtokarski  seems less of an agent issue and the way you set up your application or instance
