### ISSUE TITLE
Allow for .yaml extension of appspec

### ISSUE THREAD

**Issue by lc-nyovchev** [aws/aws-codedeploy-agent#182]
According to this one:

https://stackoverflow.com/questions/21059124/is-it-yaml-or-yml/21059164

**.yaml is the preferred extension to .yml**

I think it does make sense that appspec could be appspec.yml AND appspec.yaml. A current codeDeploy task with appspec.yaml instead of appspec.yml fails with:

`The CodeDeploy agent did not find an AppSpec file within the unpacked revision directory at revision-relative path "appspec.yml". The revision was unpacked to directory .... ... ...`

The proper approach should be to allow for the deprecated .yml format but also to allow for .yaml file as that's the recommended extension.

**Comment by annamataws** [comment]
Added to our backlog.

Thank you.

**Comment by lc-nyovchev** [comment]
Hi guys, was wondering if there is some jira or something where we can see the backlog?

**Comment by Raunak2203** [comment]
This didn't fix the issue.

**Comment by omar-dulaimi** [comment]
I just faced the same issue. We have two pipelines, one for deploying on EC2 and the other on Fargate. The first requires .yml and the other one .yaml!

I had to make a custom script to fix this NON-issue.

**Comment by lc-nyovchev** [comment]
@rohkat-aws @vrr-21 I made the PR for this one some time ago. Any chance you guys can take a look at the PR :arrow_double_up:  and give me some feedback :pray: ?

**Comment by philstrong** [comment]
We'll take a look
