### ISSUE TITLE
[feature] Support time_zone option for deployment logs

### ISSUE THREAD

**Issue by runlevel5** [aws/aws-codedeploy-agent#183]
The output of codedeploy agent logs, for example `/opt/codedeploy-agent/deployment-root/deployment-logs/codedeploy-agent-deployments.log` uses local time

```
[2018-08-17 14:39:48.838] [d-CD-ID][stdout] My message
```

It would be great if there is a `time_zone` option in `/etc/codedeploy-agent/conf/codedeployagent.yml
` to choose between `LOCAL` or `UTC`. 

implementation is in PR: https://github.com/aws/aws-codedeploy-agent/pull/184

**Comment by joneslee85** [comment]
@rohkat-aws https://github.com/aws/aws-codedeploy-agent/pull/184

**Comment by mwjones-aws** [comment]
Our recommended solution is to write your CodeDeploy Agent logs to CloudWatch. You can do so following [this guide](https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent-operations-cloudwatch-agent.html).
