### ISSUE TITLE
Rubygems.org has outdated aws-codedeploy-agent gem

### ISSUE THREAD

**Issue by kingdonb** [aws/aws-codedeploy-agent#187]
Is there any value in packaging this as a Ruby Gem?  I see that https://rubygems.org/gems/aws-codedeploy-agent/ is an obsolete version that was forked and maintained back in 2015, but repo has been closed and archived now.  The current instructions for agent don't prescribe installation from a gem, which is why I asked the question the way I have.

More importantly perhaps, when I went searching for "codedeploy ruby gem" to find out more, after hearing that CodeDeploy agent itself was actually written in Ruby (I am a Rubyist and that is a plus for me), well that dead fork published on rubygems.org is what came back as the top result.

First impression "hoo boy another ruby gem that nobody maintains" but as I clicked through the remaining links, I found that CodeDeploy is apparently quite serious and it looks like there have been releases since then, also there is a separate gem for aws-sdk-codedeploy which is maintained too.

Is this something that can be resolved somehow?

**Comment by rohkat-aws** [comment]
@kingdonb we don't officially support ruby code deploy agent gem, the only way to install it , is mentioned in the public docs  https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent-operations-install.html

**Comment by kingdonb** [comment]
That's fine, but you might want to find out who owns that gem and take it down then.  It's still the top result for "codedeploy ruby gem" and gives new users the wrong idea about where to begin.
