### ISSUE TITLE
codedeploy-agent auto update cron on reboot fails deployment

### ISSUE THREAD

**Issue by Ram81** [aws/aws-codedeploy-agent#188]
Codedeploy fails sometimes with an error `dpkg: error: dpkg status database is locked by another process` due to auto update cron in file `/etc/cron.d/codedeploy-agent-update`.

Is it necessary to keep these three crons (in file `/etc/cron.d/codedeploy-agent-update`) enabled
`28 12 * * * root /bin/sleep 21; /opt/codedeploy-agent/bin/update --sanity-check --upgrade deb`
`58 * * * * root /bin/sleep 21; /opt/codedeploy-agent/bin/update --sanity-check --downgrade deb`
`@reboot root /bin/sleep 45; /opt/codedeploy-agent/bin/update --sanity-check deb`

Can we remove the cron to update at the reboot time or provide some appropriate delay before triggering update to resolve the issue?

Version of codedeploy-agent : 1.0-1.1518

**Comment by rohkat-aws** [comment]
@Ram81  was there any more information in the agent logs

**Comment by Ram81** [comment]
@rohkat-aws we have a script which installs a debian file of on our servers at the time of deployment and we get `dpkg: error: dpkg status database is locked by another process`  which occurs occasionally, I saw in all cases the lock was acquired by codedeploy-agent's auto updater cron's dpkg install.

To answer your question I didn't see anything unusal in agent logs

**Comment by Ram81** [comment]
@rohkat-aws why is it necessary to have a cron entry for update script on reboot?

**Comment by annamataws** [comment]
Hi Ram81,

By "CodeDeploy fails", do you mean the agent is failing with that error or a deployment is failing with that error?

Thank you

**Comment by Ram81** [comment]
@annamataws deployment is failing

**Comment by mwjones-aws** [comment]
Closing this issue. We plan to remove the update script in an upcoming release. Please follow our recommended, supported approaches to update CodeDeploy agent on your fleet.

https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent-operations-update.html
