### ISSUE TITLE
codedeploy-agent.msi fails to install on Windows 2016 ending with "Error 1920...Verify that you have sufficient privileges to start system services."

### ISSUE THREAD

**Issue by ddemeyer** [aws/aws-codedeploy-agent#189]
This took me a while to figure out, so I hope this helps somebody to find the resolution quicker.

I had a successful `UserData` script that worked on Windows 2012R2, running the same failed to install CodeDeploy as a service on Windows 2016 (tried latest AMIs of WINDOWS_2016_SQL_SERVER_EXPRESS_2016 and WINDOWS_2016_SQL_SERVER_STANDARD_2016)

The `codedeploy-agent.msi` eventually fails with
`Error 1920. Service 'CodeDeploy Host Agent Service' (codedeployagent) failed to start.  Verify that you have sufficient privileges to start system services.
Action ended 15:34:15: InstallFinalize. Return value 3.
Action ended 15:34:45: INSTALL. Return value 3.
MSI (s) (9C:C0) [15:34:45:682]: Product: CodeDeploy Host Agent -- Installation failed.
MSI (s) (9C:C0) [15:34:45:702]: Windows Installer installed the product. Product Name: CodeDeploy Host Agent. Product Version: 1.0.1.1518. Product Language: 1033. Manufacturer: Amazon Web Services. Installation success or error status: 1603.`

The `1920` is just a general Oops error. Digging deeper with ProcessExplorer I saw multiple attempts to start `winagent.exe` that all *silently* failed without an obvious reason on missing rights.

It could be that I missed something obvious but I didn't expect Windows 2016 combined with CodeDeploy to be that obscure. Eventually read `We have a known issue on Windows 10 that the installer failed to update the service configuration, which cause the installation to fail.` in #81 It would be nice that this known issues list would pop up in search results.

So the solution is to add Windows Defender exclusions before starting the installer. I used the following PowerShell statements that require Administrator
`Write-Host ("Adding Windows Defender exclude for CodeDeploy...")`
`Add-MpPreference -ExclusionPath ("C:\ProgramData\Amazon\CodeDeploy","$env:windir\Temp")`

**Comment by rohkat-aws** [comment]
@ddemeyer thanks for posting the fix.

**Comment by ddemeyer** [comment]
By simply closing, is it then fair to assume that CodeDeploy is not a first-class citizen for Windows 2016 (and above), so we should look for an alternative? Working nicely with Windows Defender which comes with the OS would be a must.

**Comment by rohkat-aws** [comment]
@ddemeyer we are looking at options and have added it internally as a task to work on.

**Comment by AnthonyNeace** [comment]
Noting here that my team encountered this issue today and proposed Windows Defender exclusion resolved it.

**Comment by samueltos** [comment]
Thank you.

**Comment by johnhaczewski** [comment]
update; this fix still works (Windows Server 2019 Standard v1809)

**Comment by eliasbedmar** [comment]
@ddemeyer - thank you so much for sharing your fix, it's saved a lot of time for us!

**Comment by Wildpipe** [comment]
Still happening in 2021

**Comment by brianhatchet** [comment]
A thousand times thank you @ddemeyer .  Your fix unblocked a troublesome agent on Windows Server 2019!

**Comment by Kavya9935** [comment]
The solution worked for Microsoft Windows Server 2019 (AMI-Windows_Server-2019-English-Full-Base-2022.02.10) as well.

**Comment by calumsult** [comment]
...and still relevant with a Windows Server 2025 AMI. Wow...
