### ISSUE TITLE
Deployment fails after AWS CodeDeploy agent runs with user profiles other than root

### ISSUE THREAD

**Issue by vikrantgargyml** [aws/aws-codedeploy-agent#191]
CodeDeploy is failing in Application stop with Error - [stderr]su: must be run from a terminal.
Our application_stop.sh file 

#!/bin/bash
. $(dirname $0)/constants.sh
service $application_name-$environment stop
#Stop the server application

#Force kill server if something is still running on its port.
pid=`lsof -t -i:$server_port`
if [ "$pid" != "" ]
then # Kill the running process
    kill -9 $pid 2>/dev/null || :
fi

#To remove the current PID file
if [ -e $pid_path ]
then
  test -x $DAEMON || exit 0
  set -e
  # To kill the current process
   kill -9 `cat $pid_path` 2>/dev/null || :
  rm -f $pid_path
fi

Our appspec.yml file

#Deployment spec file for AWS CodeDeploy.
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/sequoia-api-backend-code-deploy-source
hooks:
  ApplicationStop:
    - location: deploy-scripts/application_stop.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: deploy-scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: deploy-scripts/after_install.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: deploy-scripts/application_start.sh
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: deploy-scripts/validate_service.sh
      timeout: 300
      runas: ubuntu

Steps followed to run CodeDeploy Agent with ubuntu user.
https://aws.amazon.com/premiumsupport/knowledge-center/codedeploy-agent-non-root-profile/

**Comment by annamataws** [comment]
Hi vikrantgargyml,

Can you please add logs so we can get more details?

Thank you

**Comment by briananstett** [comment]
If hook scripts (specifically AfterInstall) are run from the source directory, `/opt/codedeploy-agent/deployment-root/deploy-group/deployment-id/deployment-archive `, how can  a different user specified with the `runas` directive execute those scripts?

By default, the codedeploy agent runs as root, this results in the source files being owned by root
```
myuser@compute3:/opt/codedeploy-agent/deployment-root/xxx/yyy/deployment-archive$ ll
total 96
drwxr-xr-x 8 root root 4096 Dec 11 14:32 ./
drwxr-xr-x 4 root root 4096 Dec 11 14:32 ../
-rw-r--r-- 1 root root  387 Dec 11 14:32 appspec.yml
drwxr-xr-x 2 root root 4096 Dec 11 14:32 bin/
-rw-r--r-- 1 root root  765 Dec 11 14:32 buildspec.yml
drwxr-xr-x 2 root root 4096 Dec 11 14:32 config/
drwxr-xr-x 2 root root 4096 Dec 11 14:32 scripts/
```

```
hooks:
  AfterInstall:
    - location: scripts/bundle_install.sh
      runas: myuser
```
If I specified one of my scripts should be runas `myuser` and the script were truly executed from the `myuser` user, they would get permission errors correct?

**Comment by alleynec** [comment]
I'm having the same issues after executing the steps in the following link:

https://aws.amazon.com/premiumsupport/knowledge-center/codedeploy-agent-non-root-profile/

**Comment by shijin-p** [comment]
Also getting similar error. See my appspec.yml and error I got below.

`version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/myapp
permissions:
   - object: /home/ubuntu/myapp
     pattern: "**"
     owner: ubuntu
     group: ubuntu
     mode: 755
     type:
       - file
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      runas: root
  AfterInstall:
    - location: scripts/start_server
      runas: root`


`The CodeDeploy agent did not find an AppSpec file within the unpacked revision directory at revision-relative path "appspec.yml". The revision was unpacked to directory "/opt/codedeploy-agent/deployment-root/66d94834frcq3d4rq3fb11559012fa/d-D2xr4xTX/deployment-archive", and the AppSpec file was expected but not found at path "/opt/codedeploy-agent/deployment-root/66d94xq4x4x1-bd89-fb11559012fa/d-DxMTX/43xrdeployment-archive/appspec.yml". Consult the AWS CodeDeploy Appspec documentation for more information at http://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file.html`

**Comment by aditya-intellimedia** [comment]
Hi. So are there any updates to this issue? I'm also facing the same issue.

**Comment by mpdude** [comment]
Maybe this requires some additional config for the `sudo` command?

**Comment by yuanzhedong** [comment]
> I'm having the same issues after executing the steps in the following link:
> 
> https://aws.amazon.com/premiumsupport/knowledge-center/codedeploy-agent-non-root-profile/

I got the same issue

**Comment by yuanzhedong** [comment]
remove `runas` will fix this issue: https://stackoverflow.com/questions/48159084/issue-running-linux-aws-codedeploy-agent-in-non-root-context

Also remember to prev deployment appspec.yml if you have hook to stop the application, since code-deploy agent to use prev appspec with `runas` to try to stop the current applicaiton.

**Comment by ceyhuncfc9** [comment]
I know this is an old issue, however it took me a couple of days to actually find a good workaround for this problem so I'm also leaving it here in case anyone else is having the same troubles.

Like everyone stated the `runas` option does not work as expected, so after you remove `runas` you can modify your script to change to the user you originally wanted to run the script.

```
#!/bin/bash
sudo -i -u ec2-user bash << EOF
echo "Running as ec2-user"
cd /home/ec2-user/project-dir
pm2 startOrReload ecosystem.config.js
EOF
echo "Back to root"
```

Hope this helps.

**Comment by mwjones-aws** [comment]
We were not able to reproduce this problem on Ubuntu.

Does the user that's running the agent have permission to `su` as the `runas` user without specifying a password?
