### ISSUE TITLE
Ruby process high memory and mem alloc fail when install target drive does not exist

### ISSUE THREAD

**Issue by deejvince** [aws/aws-codedeploy-agent#192]
Deploying to an instance where the target drive did not exist (I tried to deploy to drive D in Windows 2008 R2),
Caused the ruby process to quickly climb to 1.2 GB ram and delployment failed due to unable to allocate memory.

Suggest to add a target check the in the beginning of the Install stage.

**Comment by annamataws** [comment]
Thank you. We will look into this and add it to our backlog.

**Comment by keithcyu** [comment]
Windows 2008 R2 support has ended on January 14, 2020. Feel free to re-open the ticket if you observe the same issue with supported operating system.

https://docs.microsoft.com/en-us/windows-server/get-started/extended-security-updates-overview
