### ISSUE TITLE
Add configuration option for AWS CodeDeploy logs retention in  /var/log/aws/codedeploy-agent folder

### ISSUE THREAD

**Issue by hegyre** [aws/aws-codedeploy-agent#193]
Hello team,

From this AWS doc:
https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent.html#codedeploy-agent-revisions-logs-cleanup

> AWS CodeDeploy logs: For Amazon Linux, Ubuntu Server, and RHEL instances, the AWS CodeDeploy agent rotates the log files under the /var/log/aws/codedeploy-agent folder. The log file is rotated at 00:00:00 (instance time) daily. Log files are deleted after seven days. The naming pattern for rotated log files is codedeploy-agent.YYYYMMDD.log.

That's a shame the logs retention is not configurable.

Only 7 days is sometimes too short, especially when we need to debug things.

Please could you make this configurable ?

I would also suggest if the value is 0, then it will allow us to configure this via traditionnal logrotate service.

Thanks in advance.

**Comment by mercora** [comment]
I would prefer to rotate the log files with logrotate too.

**Comment by annamataws** [comment]
Feature request has been added to our backlog.

**Comment by mwjones-aws** [comment]
You can persist CodeDeploy Agent logs for longer than 7 days by writing them to CloudWatch. https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent-operations-cloudwatch-agent.html
