### ISSUE TITLE
AppSpec Files on an EC2/On-Premises Compute Platform - Add support for .json files

### ISSUE THREAD

**Issue by morgangraphics** [aws/aws-codedeploy-agent#194]
JSON support is available on the Lambda platform so I am not sure why it's just limited to that and not the EC2 platform. 

The use case it that I'm trying to keep the JavaScript app/project as simple as possible. Meaning that adding config files as .json and .yml seems a bit silly. While the bar is not that great for conversion between the formats, consistency is pretty key within projects.

**Comment by mwjones-aws** [comment]
Hi closing as this is not on our roadmap and it's been a few years.

Please re-open if supporting appspec.json for EC2/on-premise would help you. Thanks!
