### ISSUE TITLE
No support for alpine linux

### ISSUE THREAD

**Issue by JonRowe** [aws/aws-codedeploy-agent#197]
## Environment

Alpine Linux 3.7 with Ruby 2.4.3.

## Behaviour

```
$  sudo ./install auto
I, [2018-11-21T17:20:58.200067 #3343]  INFO -- : Starting Ruby version check.
I, [2018-11-21T17:20:58.200324 #3343]  INFO -- : Starting update check.
I, [2018-11-21T17:20:58.200435 #3343]  INFO -- : Attempting to automatically detect supported package manager type for system...
E, [2018-11-21T17:20:58.204414 #3343] ERROR -- : Could not detect any supported package managers.
```

## Expected behaviour

Detects apk and installs code-deploy agent.

**Comment by philstrong** [comment]
Is this Alpine Linux issue or Ruby 2.4.3 issue?

**Comment by JonRowe** [comment]
From memory (2 years ago now) it was that aws-codedeploy-agent coudln't find a package manager, so presumedly it has no knowledge of alpine, realistically, this is not something Alpine or Ruby can solve, its a problem directly with this package.

**Comment by JonRowe** [comment]
Given this is more than two years old and I no longer use aws-codedeploy, Alpine or Ruby 2.4.3, I'm closing this as stale
