### ISSUE TITLE
use cloudformation to create test environment

### ISSUE THREAD

**Issue by jdrago999** [aws/aws-codedeploy-agent#20]
why was this not done via cloudformation in the first place??

**Comment by suryanarayanan** [comment]
Cloudformation might be an overkill for the small set of resources that we stand up & tear down during test. We wanted to have some flexibility in creating and re using resources going forward. 
For e.g, 
- the tests could be easily updated to use existing roles and instances via config parameters especially for the users who want to have a very minimal permissions on their test credentials.
- Using existing resources could also speed up the development-test cycle. For e.g, if I run the tests in an ec2 instance it would be faster for me to re use the same instance to do the deployment.

Also, cloudformation is one extra dependency which could fail and the test should still take care of cleaning up resources on failures.
Being said that, you are welcome to throw in a cloudformation template to create the basic set of test resources and I'd be happy to review and merge it in.

Thanks,
Surya.
