### ISSUE TITLE
Deployment does not work without instance profile

### ISSUE THREAD

**Issue by yairt** [aws/aws-codedeploy-agent#204]
Issue is relevant in Github application deployment use case, when S3 application deployment is not needed.
Deployment does not work when no Instance Profile is associated with the EC2 instance.
When I associate a Role with EC2 trust entity **with no permissions** it works.
It seems agent requires some Role to be associated because it calls AssumeRole API.

Documentation states EC2 instance to be used with CodeDeploy should have S3 access for s3 application deployments. It does not state Github application deployment use case.

**Comment by huribeir** [comment]
Even when you're using GitHub, the instance profile is required and used to prove the host's identity with the CodeDeploy service.

**Comment by yairt** [comment]
What does it proves? (when I associate Instance Profile with only trust relationship of ec2 but **without any permissions**)
