### ISSUE TITLE
Bug in update script ARGV count

### ISSUE THREAD

**Issue by b27cs** [aws/aws-codedeploy-agent#212]
script checks for the max count of command line arguments, and limits this value to 4, but it needs to be 5! see line 135 in update script:

(Actually, should have better way of counting the args based on what's defined, rather than just hard-coding the number.. will just break again if somebody forgets to update this value the next time an arg option is added..)

This leads to failure in the following scenrio:

/opt/codedeploy-agent/bin/update --proxy http://myproxy:8888 --sanity-check --upgrade deb

  def parse_args()
    if (ARGV.length > 4)
      usage
      @log.error('Too many arguments.')
      exit(1)
    elsif (ARGV.length < 1)
      usage
      @log.error('Expected package type as argument.')
      exit(1)
    end

**Comment by mwjones-aws** [comment]
Closing this issue. We plan to remove the update script in an upcoming release. Please follow our recommended, supported approaches to update CodeDeploy agent on your fleet.

https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent-operations-update.html
