### ISSUE TITLE
No option or config for cron update script to run with proxy

### ISSUE THREAD

**Issue by b27cs** [aws/aws-codedeploy-agent#213]
after code-deploy agent install finishes, it makes a cron file to check for updates, but there is no option or config file provided to specify that this must run with proxy..

So in the file that gets generated: /etc/cron.d/codedeploy-agent-update the command is given as:
/opt/codedeploy-agent/bin/update --sanity-check --upgrade deb

and if this runs on machine behind proxy, it crashes, which then results in the code-deploy agent service exiting, which then breaks the commit pipeline when it runs..

And this is closely tied to the other issue I just opened since at the moment, even if the proxy option is manually added to the cron file, it still breaks due to the ARGV count issue.

**Comment by brblck** [comment]
The cron update method has been deprecated for the agent.

Please upgrade to v1.1.2 (our latest stable version):
https://aws.amazon.com/about-aws/whats-new/2020/08/aws-codedeploy-agent-improved-compatibility-amazon-linux-windows-ubuntu/
