### ISSUE TITLE
Add support for ruby 2.6 

### ISSUE THREAD

**Issue by wissam** [aws/aws-codedeploy-agent#214]
Installation fails for ruby 2.6.x
Of course since only up to 2.5 is supported as seen in here:

def supported_ruby_versions
    ['2.5', '2.4', '2.3', '2.2', '2.1', '2.0']
end

**Comment by mujz** [comment]
Any status on this one please? I'm having this issue too.

**Comment by charusat09** [comment]
Rails 6 already out and we want to upgrade our application using ruby 2.6 and rails 6. Waiting for this issue to be fixed. Any update on this?

**Comment by wbotelhos** [comment]
My workaround, to use Ruby 2.6.5, is replace the version number before execute the script.

Chef example:

```
execute 'codedeploy_download' do
  command 'wget https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/install'
  cwd     '/tmp'
end

execute 'codedeploy_install' do
  command %(sed -i "s/'2.5/'2.6/" install && chmod +x ./install && ./install auto)
  cwd     '/tmp'
end
```

**Comment by Tietew** [comment]
`ruby2.6` is available on `amazon-linux-extras` repositories. Any updates?

**Comment by charusat09** [comment]
I think CodeDeploy supports new 2.7 as well after merging this PR: https://github.com/aws/aws-codedeploy-agent/pull/254/files. Thanks.

**Comment by wissam** [comment]
2.6 is now supported , closing the ticket
