### ISSUE TITLE
'install auto' fails to find yum

### ISSUE THREAD

**Issue by Akin2Silver** [aws/aws-codedeploy-agent#216]
When launching a fresh docker container of Amazon Linux2 and attempting to install i get the following output. 
```
bash-4.2# ./install auto
I, [2019-06-05T02:38:12.318108 #152]  INFO -- : Starting Ruby version check.
I, [2019-06-05T02:38:12.318205 #152]  INFO -- : Starting update check.
I, [2019-06-05T02:38:12.318768 #152]  INFO -- : Attempting to automatically detect supported package manager type for system...
E, [2019-06-05T02:38:12.327198 #152] ERROR -- : Could not detect any supported package managers.
```

Looks like the auto detect in the install script can't find Yum.

To reproduce, `docker run  -it amazonlinux /bin/bash`
```
yum -y update && yum -y install awscli ruby rubygems
```
setup aws creds
```
cd /tmp/
aws s3 cp s3://aws-codedeploy-ap-southeast-2/latest/install . --region ap-southeast-2
chmod +x ./install
./install auto
```

**Comment by Akin2Silver** [comment]
Sorry thought i was mistaken but looks like it's true. 

The test looks to be doing a which check and that wont work everywhere. 
https://stackoverflow.com/questions/592620/how-to-check-if-a-program-exists-from-a-bash-script

**Comment by ljwagerfield** [comment]
You need to `yum install which`.
