### ISSUE TITLE
Log actions during a deployment

### ISSUE THREAD

**Issue by jdrago999** [aws/aws-codedeploy-agent#22]
I use Codedeploy to kick off a few things, one of which is a Chef solo run.

Tailing /var/log/aws/codedeploy-agent/codedeploy-agent.log reveals almost nothing of value, certainly none of the copious logs from performing the Chef run.

Suggestion: Make it very clear *where* the log for each Codedeploy deployment goes, and have *that* log include all output from its child tasks (such as Chef runs, in this case).

If there was some reason why providing visibility into what Codedeploy is doing was intentionally left out, and it will take a significant effort to add it back in, please make it known.

Thanks.

**Comment by nestorpina** [comment]
Have you looked at `/opt/codedeploy-agent/deployment-root/<agent-id?>/<deployment-id>/logs/scripts.logs`?

It's somewhat hidden, but I found my scripts logs there. I don't know what the first id is, I suppose it's the agent id...

**Comment by jdrago999** [comment]
Thanks, @nestorpina - `/opt/codedeploy-agent/deployment-root/9fb43944-176a-43f3-8093-3a53bc771e35/d-YVJIZUFXA/logs/scripts.log` how did I not see this before?

**Comment by brian-lamb-software-engineer** [comment]
I use code deploy, and am getting a failure.  Maybe im not sure if its the actual "agent" im using, but i deploy from cli, so i suspect that is the agent. However i cant find the logs in /var/log, (no aws folder in there), nor /opt (only a puppetlabs folder in there), on either the controller (where deploys happen), or the master.
