### ISSUE TITLE
Deploying Ruby application with Bundler to EC2

### ISSUE THREAD

**Issue by mknycha** [aws/aws-codedeploy-agent#224]
First of all, thanks for a great tool.
Recently I tried to deploy an app written in Ruby to EC2 instance. This has some Gem dependencies managed by Bundler, so I run `bundle install` in my `AfterInstall` hook.

### The problem

When running this script, I get errors like `bundle binary is not found`, or `Gem::Ext::BuildError: ERROR: Failed to build gem native extension.` It is a bit strange to me, since I have no issues running `bundle install` manually in bash on my instance. 

### Solution

I fixed this with changing my script to:
• Install bundler somewhere under PATH
• Install dependencies (i.e. c++ garbage collector, ruby development kit)

All my scripts are in this [gist](https://gist.github.com/mknycha/1262a21b878fa660ac6f773a01a1cbf0).

### Expectation

I thought that since I can run `bundle install` when connecting through ssh to my instance, it will work in the scripts too. I am not sure if installing env dependencies for every gem is the right way.

I wanted to ask:
1. What is the environment in which hook scripts are run?
2. Is the above right solution for using Bundler, or is there a better way?

**Comment by mwjones-aws** [comment]
Please track #301, which talks about options for separating Ruby executable/dependencies for CodeDeploy Agent versus other applications running on the instance.
