### ISSUE TITLE
Allow to start automatically at boot time?

### ISSUE THREAD

**Issue by simplesteph** [aws/aws-codedeploy-agent#225]
If I restart my EC2 instance, the codedeploy agent stops and doesn't restart.
I didn't find anywhere documented for that scenario, and running `sudo service codedeploy-agent enable` is not supported.

Can you please advise?

**Comment by brblck** [comment]
Can you tell us more about your system? What OS are you running?

**Comment by philstrong** [comment]
Closing as comms > 6 months
