### ISSUE TITLE
Error when try to install codedeploy-agent

### ISSUE THREAD

**Issue by zadorozhny** [aws/aws-codedeploy-agent#226]
when I use sudo ./install deb this error appears

Error installing /tmp/codedeploy-agent_1.0-1.1597_all.tmp-20191007-2682-1whwowb.deb.

**Comment by brblck** [comment]
Looks like you forgot to tell us more details about your system. 

What OS are you running? Is it [one of our supported operating systems](https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent.html#codedeploy-agent-supported-operating-systems)?
Are you following [this guide for installation steps](https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent-operations-install.html)?

**Comment by philstrong** [comment]
Closing as comms > 6 months
