### ISSUE TITLE
Windows 2019 compatibility?

### ISSUE THREAD

**Issue by lauri-laanti-heeros** [aws/aws-codedeploy-agent#231]
Is it possible to install agent to Windows Server 2019?

Install attempts currently fail with:
```
MSI (s) (50:9C) [14:17:27:640]: Product: CodeDeploy Host Agent Updater -- Error 1721. There is a problem with this Windows Installer package. A program required for this install to complete could not be run. Contact your support personnel or package vendor. Action: RemoveScheduledTask, location: C:\ProgramData\Amazon\CodeDeployUpdater\bin\, command: "C:\Windows\SysWOW64\SCHTASKS.EXE" /DELETE /TN "CodeDeployAgentUpdater" /F 

Error 1721. There is a problem with this Windows Installer package. A program required for this install to complete could not be run. Contact your support personnel or package vendor. Action: RemoveScheduledTask, location: C:\ProgramData\Amazon\CodeDeployUpdater\bin\, command: "C:\Windows\SysWOW64\SCHTASKS.EXE" /DELETE /TN "CodeDeployAgentUpdater" /F 
Action ended 14:17:27: InstallFinalize. Return value 3.
Action ended 14:17:27: INSTALL. Return value 3.
MSI (s) (50:9C) [14:17:27:671]: Product: CodeDeploy Host Agent Updater -- Configuration failed.

MSI (s) (50:9C) [14:17:27:671]: Windows Installer reconfigured the product. Product Name: CodeDeploy Host Agent Updater. Product Version: 1.0.0.0. Product Language: 1033. Manufacturer: Amazon Web Services. Reconfiguration success or error status: 1603.
```

**Comment by vlmironov** [comment]
Yes it is possible.

**Comment by Christianhart** [comment]
We've been installing codedeploy on server 2019 for over 6 months. There is a know bug which happens intermittently every few days and requires the service to be restarted though. Our workaround for that bug is monitoring the codedeploy log file and restarting the service whenever the error comes up.

Here is our powershell for automating the deploy:
```#Retrieve AWS CodeDeploy from AWS Provided bucket
Write-host "Getting CodeDeploy from AWS"
Invoke-WebRequest -Uri 'https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/codedeploy-agent.msi' -OutFile $TempDir\codedeploy-agent.msi

#Install AWS CodeDeploy and starting service
Write-Host ("Adding Windows Defender exclude for CodeDeploy...")
Add-MpPreference -ExclusionPath ("C:\ProgramData\Amazon\CodeDeploy","$env:windir\Temp")
Write-host "Installing Code Deploy CodeDeploy"
Start-Process msiexec.exe "/i $TempDir\codedeploy-agent.msi /quiet /log $TempDir\host-agent-install-log.txt" -wait
```

**Comment by vlmironov** [comment]
@Christianhart 
I have created an issue for this exact problem I do have as well:
https://github.com/aws/aws-codedeploy-agent/issues/234

**Comment by jvrdev** [comment]
This is Incredibly disruptive. We are also experiencing this issue.

**Comment by Christianhart** [comment]
@jvrdev and @lauri-laanti-heeros our long term solution is moving away from Windows servers and to Linux containers. Fixes many issues including codedeploy problems. AWS Codebuild + AWS ECS + AWS Fargate is pretty awesome, much cheaper than running servers, and easy to implement. Thankfully all our apps are capable of being run on Linux.

**Comment by brblck** [comment]
Our full list of supported operation systems is available here:
https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent.html#codedeploy-agent-supported-operating-systems

Please upgrade to v1.1.2 (our latest stable version) where we have improved support for Windows 2019.
https://aws.amazon.com/about-aws/whats-new/2020/08/aws-codedeploy-agent-improved-compatibility-amazon-linux-windows-ubuntu/
