### ISSUE TITLE
CommandPoller: ArgumentError - string contains null byte

### ISSUE THREAD

**Issue by festavro** [aws/aws-codedeploy-agent#233]
Hello Everyone

We have an application that is deployed in an EC2 instance by Code Deploy, and somehow the deploy started failing for a reason we cannot identify. The difference from the last sucessfull deploy and the failed ones are a simple commit on the code of the application, nothing to do with the deploy.

The error is happening on the event ApplicationStop. Is described as Unknown Error and has the following description: 

> string contains null byte

I've connected to the Instance and checked the logs on C:\ProgramData\Amazon\CodeDeploy\log\codedeploy-agent-log.txt and I've found the following error:

`2020-01-07T14:12:39 ERROR [codedeploy-agent(5748)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Error during perform: ArgumentError - string contains null byte - C:/Windows/TEMP/ocr72E5.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/hook_executor.rb:99:in `join'`

The region of the instance is us-east-2. I've tested deploying at our environment on the region us-west-2 and it still works.

Could someone please help me with that?

**Comment by AlexanderSchlecht** [comment]
I was having the same issue today, I was able to fix it by uninstalling the agent then deleting the CodeDeploy folder under ProgramData/Amazon. Then reinstalling the agent. The odd thing we noticed was that this issue was only on our UAT account which looks just like our DEV account, but DEV had no issues deploying.

**Comment by brblck** [comment]
Please upgrade to v1.1.2 (our latest stable version) and let us know if you're still experiencing this issue.
https://aws.amazon.com/about-aws/whats-new/2020/08/aws-codedeploy-agent-improved-compatibility-amazon-linux-windows-ubuntu/
