### ISSUE TITLE
CodeDeploy Host Agent Service becomes unresponsive after being idle on Windows Server 2019

### ISSUE THREAD

**Issue by vlmironov** [aws/aws-codedeploy-agent#234]
OS: Windows Server 2019
AWS CodeDeploy Agent version: 1.0.1.1597

Issue: 
Deployment fails with the following error message:

> Error during deployment: code HEALTH_CONSTRAINTS, message 'The overall deployment failed because too many individual instances failed deployment, too few healthy instances are available for deployment, or some instances in your deployment group are experiencing problems.'.

Temp workaround:
Go to Services and restart CodeDeploy Host Agent Service then retry deployment which succeeds after the service restart.

Note:
The issue repeats over and over after the server idles for some time not receiving deployment packages.

**Comment by brblck** [comment]
Please upgrade to v1.1.2 (our latest stable version) where we have improved support for Windows 2019.
https://aws.amazon.com/about-aws/whats-new/2020/08/aws-codedeploy-agent-improved-compatibility-amazon-linux-windows-ubuntu/
