### ISSUE TITLE
Installation fails on Ubuntu 14.04.6 LTS

### ISSUE THREAD

**Issue by edias** [aws/aws-codedeploy-agent#240]
I'm following the official guide to install code deploy on Ubuntu 14.04.6 LTS but its failing with error:

`Setting up Local Package Process
Examining /tmp/codedeploy-agent-1.0-1.1597.noarch.tmp-20200410-17329-d9k7hd.rpm: codedeploy-agent-1.0-1.1597.noarch
Marking /tmp/codedeploy-agent-1.0-1.1597.noarch.tmp-20200410-17329-d9k7hd.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package codedeploy-agent.noarch 0:1.0-1.1597 will be installed
--> Processing Dependency: /bin/sh for package: codedeploy-agent-1.0-1.1597.noarch
--> Processing Dependency: /bin/sh for package: codedeploy-agent-1.0-1.1597.noarch
--> Processing Dependency: /bin/sh for package: codedeploy-agent-1.0-1.1597.noarch
--> Processing Dependency: /bin/sh for package: codedeploy-agent-1.0-1.1597.noarch
--> Processing Dependency: /bin/sh for package: codedeploy-agent-1.0-1.1597.noarch
--> Processing Dependency: /bin/sh for package: codedeploy-agent-1.0-1.1597.noarch
--> Processing Dependency: /bin/sh for package: codedeploy-agent-1.0-1.1597.noarch
--> Processing Dependency: /bin/sh for package: codedeploy-agent-1.0-1.1597.noarch
--> Finished Dependency Resolution
Error: Package: codedeploy-agent-1.0-1.1597.noarch (/codedeploy-agent-1.0-1.1597.noarch.tmp-20200410-17329-d9k7hd)
           Requires: /bin/sh
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
E, [2020-04-10T11:19:00.488315 #17329] ERROR -- : Error installing /tmp/codedeploy-agent-1.0-1.1597.noarch.tmp-20200410-17329-d9k7hd.rpm.`

**Comment by brblck** [comment]
Following the [CodeDeploy agent install guide we have here](https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent-operations-install-ubuntu.html), I wasn't able to reproduce this issue on Ubuntu 14.04.

Can you provide clear steps to reproduce the issue you're running into?

**Comment by brblck** [comment]
Please upgrade to v1.1.2 (our latest stable version) where we have improved support for various verisons of Ubuntu.
https://aws.amazon.com/about-aws/whats-new/2020/08/aws-codedeploy-agent-improved-compatibility-amazon-linux-windows-ubuntu/
