### ISSUE TITLE
Codedeploy not getting installed on Ubuntu focal because of ruby 2.7

### ISSUE THREAD

**Issue by shivansh931** [aws/aws-codedeploy-agent#243]
install: line 9: class: command not found
install: line 11: syntax error near unexpected token `('
install: line 11: `    undef_method m unless m =~ /(^__|^send$|^object_id$)/'

**Comment by brblck** [comment]
Closing as duplicate of https://github.com/aws/aws-codedeploy-agent/issues/239.
