### ISSUE TITLE
version 1.1.2 is latest but missing release information

### ISSUE THREAD

**Issue by jack1902** [aws/aws-codedeploy-agent#259]
## Description

When can we expect Release Information for `v1.1.2` which is available from the S3 bucket as the `latest` version?

### Steps to reproduce

```bash
# Run the following to get the LATEST_RELEASE
curl https://aws-codedeploy-eu-west-1.s3.amazonaws.com/latest/LATEST_VERSION

# output
{"rpm":"releases/codedeploy-agent-1.1.2-1855.noarch.rpm","deb":"releases/codedeploy-agent_1.1.2-1855_all.deb","msi":"releases/codedeploy-agent-1.1.2.1855.msi"}
```

I would have expected that the output be `1.1.1` from the GitHub release page but this is not the case

### Version installed
Using https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent-operations-version.html#codedeploy-agent-operations-version-ubuntu to see the version currently installed

```bash
sudo dpkg -s codedeploy-agent

# Output
Package: codedeploy-agent
Status: install ok installed
Section: admin
Maintainer: Amazon Web Services
Architecture: all
Version: 1.1.2-1855
Depends: ruby2.0 | ruby2.1 | ruby2.2 | ruby2.3 | ruby2.4 | ruby2.5 | ruby2.6 | ruby2.7
Conffiles:
 /etc/codedeploy-agent/conf/codedeployagent.yml e62bb96fb488e166742f963bcb8713b8
Description: CodeDeploy instance agent is responsible for doing the actual work of deploying software on an EC2 instance.
```

**Comment by Helen1987** [comment]
@jack1902 Agent release is taking a few days. We publish new release information after Agent is available in major regions. New [release 1.1.2](https://github.com/aws/aws-codedeploy-agent/releases/tag/v1.1.2) is available now
