### ISSUE TITLE
CodeDeploy Agent does not work with Instance Metadata V2

### ISSUE THREAD

**Issue by gelouko** [aws/aws-codedeploy-agent#263]
# Problem
When trying to use the CodeDeploy Agent with an EC2 instance that has Instance Metadata V2 active, the following errors occurs during a deployment:

```
booting child: error during start or run: RuntimeError - HTTP error from metadata service, code 401 - /opt/codedeploy-agent/lib/instance_metadata.rb:47:in `block in http_get`
```

# How to Reproduce
Create a deployment group with an EC2 instance that has instance metadata v2 active and try to deploy to it

---

Checking the code, looks like the `instance_metadata` code does not have the capability of retrieving the required token to be used with the instance metadata v2 feature.
Is there a workaround on this?

If not, I'd enjoy contributing with a Pull Request. Any ideas on that?

Thanks!

**Comment by brblck** [comment]
Instance Metadata v2 support will be available in v1.2.0 of the agent which should be available in all regions before the end of August.
