### ISSUE TITLE
[Windows] Agent silently hangs forever if hook script doesn't close STDOUT

### ISSUE THREAD

**Issue by moloch--** [aws/aws-codedeploy-agent#288]
On Windows I need the CodeDeploy Agent to simply start a plain `.exe` (non-service) process on the server for the `ApplicationStart`, but this does not seem to be possible. It seems to be related to how the Agent runs the deployment scripts, similar issues [here](https://github.com/aws/aws-codedeploy-agent/issues/118).  

However, the problem doesn't seem to have ever been fixed, and the only workarounds I can find are for Linux (the AWS documentation also only provides work around examples for Linux).

I have a script that invokes the server process in what should be a non-blocking way, it works fine when running the script from the command line:

`start.bat`
```
start C:\server.exe
```

Output:
```
Script at specified location: scripts/start.bat failed to close STDOUT
```

I've also tried these but they don't work:
```
cmd.exe /c "start C:\server.exe"
```
```
start C:\server.exe 2>NUL
```

What's really annoying is that the process gets created but the Agent still reports the deployment as a failure.

**Comment by hashitha** [comment]
I have run in to the same issue, any updates on this?

**Comment by moloch--** [comment]
I developed a workaround using PowerShell, as far as I know this bug has not been fixed:

```
powershell.exe Start-Process -WorkingDirectory C:\ -FilePath C:\foo.exe
```

**Comment by philstrong** [comment]
Does this fix the issue https://stackoverflow.com/questions/42222004/run-exe-in-background

**Comment by hashitha** [comment]
This is what worked for me

create a script name `start.ps1`
with the following contents
`Start-Process -FilePath "C:\QUBS\server\Server.exe"`

also for some reason, this only works if I invoke using command line
e.g. `aw deploy create-deployment --application-name ...`

Just another note:
If I use AWS Pipeline then it fails like 90% of the time and only works if I clear the temp files of AWS deploy %Programdata% then restart the EC2 machine. I was using Windows 2022 server. Maybe this is not supported yet

**Comment by mwjones-aws** [comment]
Closing as not planned.

You need to start your application in a process other than the one CodeDeploy is using to run your hook script. `Start-Process` accomplishes this. You can also install your application as a service.
