### ISSUE TITLE
Codedeploy agent seems to stop randomly so deployment tends to fail at "BeforeBlockTraffic"

### ISSUE THREAD

**Issue by monelgordillo** [aws/aws-codedeploy-agent#306]
This is a very strange issue.  I've been doing blue/green CodeDeploy deployments for about 2 years now.  Intermittently, deployments have been failing randomly at "BeforeBlockTraffic" on the original instance.  I've noticed that restarting the codedeploy-agent helps BeforeBlockTraffic to succeed.

`cat /opt/codedeploy-agent/.version 
agent_version: OFFICIAL_1.3.1-1880_rpm`

The EC2 is on Centos 7.  The temporary workaround is to restart the codedeploy agent regularly throughout the day.  However, I would prefer to figure out the root cause.

**Comment by mwjones-aws** [comment]
Please reopen if you're still experiencing the issue with the [latest CodeDeploy Agent](https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent.html#codedeploy-agent-version-history)
