### ISSUE TITLE
[feature]Installing CodeDeploy without Registration

### ISSUE THREAD

**Issue by lmayorga1980** [aws/aws-codedeploy-agent#315]
I would like to install code-deploy-agent without registration and pre-bake it as an AMI. Are any extra flags supported during the MSI Installation?

Are there any CLI Flags to unregister and register?

**Comment by mwjones-aws** [comment]
Hi,

Could you give us a little more detail? What tool/framework are you using to create your AMI?

**Comment by lmayorga1980** [comment]
We use **hashicorp/packer** to build AWS AMIs and we would like to perform this installation without having the Windows Service to automatically start. This way, users only have to start the Windows Service upon ec2-launch and don't have to wait much time for the installation.

**Comment by t0shiii** [comment]
I would suggest stopping the CodeDeploy Agent Service before creating the AMI.  If you need to do this in a powershell script, please use the command `Stop-Service -Name codedeployagent`
