### ISSUE TITLE
Codedeploy Agent fails after updating to Ruby 2.7.6 (Ubuntu 18.04)

### ISSUE THREAD

**Issue by airjoshb** [aws/aws-codedeploy-agent#320]
After upgrading Ruby from 2.5.9 to 2.7.6 the codedeploy agent won't start with the below that doesn't have much information. The environment uses RVM, the sys default is 2.5.9. If I switch to 2.7.6 and try and start, the issue is the same. Has anyone seen this?

codedeploy-agent.service - LSB: AWS CodeDeploy Host Agent
   Loaded: loaded (/etc/init.d/codedeploy-agent; generated)
   Active: failed (Result: exit-code) since Wed 2022-05-18 22:56:28 UTC; 3min 1s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 2015 ExecStart=/etc/init.d/codedeploy-agent start (code=exited, status=126)

May 18 22:56:28 ip-172-31-49-61 systemd[1]: Starting LSB: AWS CodeDeploy Host Agent...
May 18 22:56:28 ip-172-31-49-61 codedeploy-agent[2015]: Starting codedeploy-agent:
May 18 22:56:28 ip-172-31-49-61 systemd[1]: codedeploy-agent.service: Control process exited, code=exited status=126
May 18 22:56:28 ip-172-31-49-61 systemd[1]: codedeploy-agent.service: Failed with result 'exit-code'.
May 18 22:56:28 ip-172-31-49-61 systemd[1]: Failed to start LSB: AWS CodeDeploy Host Agent.

**Comment by airjoshb** [comment]
Thanks for the response. 

- is this an EC2 or on-premise instance? If EC2, which region and AMI are you using?

This is an EC2 Instance and the AMI is a custom built off of  Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1075-aws x86_64)

- Are you [installing CodeDeploy Agent](https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent-operations-install.html) using SSM, or by downloading it from our S3 bucket in the region?

Downloading from the S3 Bucket

- if you're using EC2, can you provide any user data you run at instance start, along with any other relevant information about your EC2 launch template?

We are using the ubuntu user and not doing anything out of the ordinary for a rails app. We launch nginx, passenger, delayed job.

**Comment by mwjones-aws** [comment]
Hi, we've released CodeDeploy Agent a few times since you reached out to us. The most recent release, [1.6.0](https://github.com/aws/aws-codedeploy-agent/issues/360), is in progress. We now support Ubuntu 22.04, as well as Ruby 3.0, 3.1 and 3.2.

Please re-open if you're still experiencing the problem with the latest version of the agent.
