### ISSUE TITLE
AWS Code deploy agent installation using "sudo ./install auto"  fails in ubuntu 22.04

### ISSUE THREAD

**Issue by fthomas82** [aws/aws-codedeploy-agent#327]
AWS Code deploy agent installation using "sudo ./install auto"  fails in ubuntu 22.04.

I refered https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent-operations-install-ubuntu.html for installation.
I don't find something in this document tell that it supports Ubuntu 22.04.

**Comment by maorweissSV** [comment]
Hi there, I have issues installing the agent on Ubuntu 22.04 as well

![image](https://user-images.githubusercontent.com/83959332/186089521-28234808-7cda-4efd-b36d-e3dbc4756eed.png)

**Comment by fthomas82** [comment]
Script would not run on Ruby3?

**Comment by maorweissSV** [comment]
That's right. Asks for Ruby2.X version

**Comment by t0shiii** [comment]
Please track #301, which talks about support for Ruby version 3.x and this is a requirement for support of Ubuntu 22.04 which we [do not officially support yet](https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent.html).
