### ISSUE TITLE
codedeploy-local error on Windows 2022: uninitialized constant InstanceMetadata::InstanceMetadataError (NameError)

### ISSUE THREAD

**Issue by Eternal21** [aws/aws-codedeploy-agent#328]
I am trying to run `codedeploy-local` on Windows 2022 server to create and test a sample deployment.  I used a minimal `appspec.yaml` file, to eliminate that as any source of errors.  I am `cd`-ing into the directory and running `codedeploy-local` command.  Instead of a deployment I end up with the following error:
```
Including Minitar via the Archive::Tar namespace is deprecated.
Starting to execute deployment from within folder Amazon/CodeDeploy/default-local-deployment-group/d-#########-local

See the deployment log
at Amazon/CodeDeploy/default-local-deployment-group/d-#########-local/logs/scripts.log for more details

C:/Users/ADMINI~1/AppData/Local/Temp/2/ocr2F8D.tmp/src/opt/codedeploy-agent/bin/codedeploy-local:134:
in `rescue in <main>': uninitialized constant InstanceMetadata::InstanceMetadataError (NameError)
from C:/Users/ADMINI~1/AppData/Local/Temp/2/ocr2F8D.tmp/src/opt/codedeploy-agent/bin/codedeploy-local:128:in `<main>'
```
There is nothing useful in the logs.

I've found a related issue here, seems to be related to Ruby, which I have zero experience with: #278

**Comment by t0shiii** [comment]
Please track #278 for this issue.
