### ISSUE TITLE
ScriptMissing and absolute paths

### ISSUE THREAD

**Issue by nathanielks** [aws/aws-codedeploy-agent#33]
Happy Thursday, All!

Running into a peculiar error: I'm getting notified that a script in my appspec.yml file doesn't exist even though it does.

```
Error Code ScriptMissing
Script Name /usr/local/codedeploy-scripts/deregister_from_elb.sh
Message Script does not exist at specified location: /usr/local/codedeploy-scripts/deregister_from_elb.sh
Log Tail LifecycleEvent - BeforeInstall
```

Are absolute paths to scripts allowed or does it have to be relative to the deployment-archive path?

**Comment by todwilli** [comment]
Hi,
With how the CodeDeploy agent is written it has to be relative to the deployment-archive path.

**Comment by nathanielks** [comment]
Okie doke. Thanks for the fast response!
