### ISSUE TITLE
How do I ensure sequential execution of deployment in deployment configuration?

### ISSUE THREAD

**Issue by Ruchira-R** [aws/aws-codedeploy-agent#335]
I don't see any option to configure - I want to execute in machine 1, mahcine 2 and then on machine 3. How do I specify the order?

**Comment by mwjones-aws** [comment]
CodeDeploy has no mechanism to enforce the order in which the instances in a deployment group receive deployments. CodeDeploy deployment groups support a deployment configuration called CodeDeployDefault.OneAtATime which will deploy to only 1 host at a time. However, this configuration makes no guarantees about the order in which hosts receive deployments. More information about CodeDeploy deployment configurations can be found  [here](https://docs.aws.amazon.com/codedeploy/latest/userguide/deployment-configurations.html) (https://docs.aws.amazon.com/codedeploy/latest/userguide/deployment-configurations.html).

Here are two ways you might do an order-aware deployment:

1. [SSM SendCommand API](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_SendCommand.html) (https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_SendCommand.html). This approach does not involve CodeDeploy at all
2. One CodeDeploy DeploymentGroup per host

Bear in mind that CodeDeploy cannot orchestrate either of these approaches for you. You will need to write code, like a Lambda function, to perform the individual deployments.
