### ISSUE TITLE
Script at specified location: scripts/install_dependencies.sh run as user root failed with exit code 1

### ISSUE THREAD

**Issue by vijay2801** [aws/aws-codedeploy-agent#341]
LifecycleEvent - BeforeInstall
Script - scripts/install_dependencies.sh
[stderr]/opt/codedeploy-agent/deployment-root/c5de5b9a-8be0-4be9-80c6-e7c1a3ddcea4/d-7TR6TBBNJ/deployment-archive/scripts/install_dependencies.sh: line 1: $'\r': command not found
[stderr]/opt/codedeploy-agent/deployment-root/c5de5b9a-8be0-4be9-80c6-e7c1a3ddcea4/d-7TR6TBBNJ/deployment-archive/scripts/install_dependencies.sh: line 3: $'\r': command not found
[stdout]Loaded plugins: extras_suggestions, langpacks, update-motd
[stdout]No package httpd available.
[stderr]Error: Nothing to do

**Comment by mwjones-aws** [comment]
Hello, please provide 
- appspec.yml
- the contents of the script

What operating system are you using?
