### ISSUE TITLE
SystemExit - Stopping CodeDeploy agent due to SSL validation error

### ISSUE THREAD

**Issue by eino-makitalo** [aws/aws-codedeploy-agent#342]
SystemExit - Stopping CodeDeploy agent due to SSL validation error

on premises code deploy agent started yesterday to fail with error above

**Comment by aj-aws** [comment]
Hello,

Which AWS region are your CodeDeploy resources in? From your host, can you reach codedeploy-commands.<region>.amazonaws.com?

**Comment by mwjones-aws** [comment]
@eino-makitalo any update?
