### ISSUE TITLE
auto-purge : deployment-root

### ISSUE THREAD

**Issue by Poil** [aws/aws-codedeploy-agent#35]
Hi,

Is there a native way to purge this directory ?
If no how are you managing it ? (post-action or via logrotate or ... ?)

Best regards,

**Comment by amartyag** [comment]
Hi Poil, we maintain deployments in this directory in a hierarchical fashion:
deployment-root 
`---- deployment-group-id
       `----deployment-id
The agent keeps last 5 deployments in the deployment-group-id folder, which also includes the last successful deployment. 

You can look at this config value here: https://github.com/aws/aws-codedeploy-agent/blob/master/lib/instance_agent/plugins/codedeploy/command_executor.rb#L13

Just in case, the detailed explanation of the agent behavior is present here:
http://docs.aws.amazon.com/codedeploy/latest/userguide/host-cleanup.html in deployment archive cleanup section

I hope that helps.

Thanks,
Amartya

**Comment by Poil** [comment]
Thanks !
