### ISSUE TITLE
Ruby 3.1 and 3.2 support

### ISSUE THREAD

**Issue by t0shiii** [aws/aws-codedeploy-agent#355]
Ruby 3.1 and 3.2 are not currently supported by the latest CodeDeploy Agent (1.5.0-57).

AL2023, which went GA on 03/15/2023 needs ruby 3.2 support.

Related issues: #351, #353

**Comment by mwjones-aws** [comment]
CodeDeploy Agent 1.6.0 adds AL2023 and Ruby 3.2 support. It has been released to most commercial regions as of this comment.

Please track release progress on https://github.com/aws/aws-codedeploy-agent/issues/360
