### ISSUE TITLE
expose git commit revision id as environmental variable to hook steps

### ISSUE THREAD

**Issue by woodhull** [aws/aws-codedeploy-agent#36]
Our CI systems precompiles some artifacts and stores them in S3 with the git revision as the unique identifier. 

We'd like the scripts that run on deploy to download the correct version based on the deployed git commit id. Right now it's awkward, since we need to query for the deployment ID and then get the git commit id from there.

**Comment by suryanarayanan** [comment]
Seems like a reasonable feature request. Thanks.

**Comment by koitsu** [comment]
Seconding this feature.  Some usage details so you understand our use case:

We don't use S3, but instead deploy via CodeDeploy directly from GitHub (GUI: "My application is stored in GitHub" checkbox).  We *really* need a way within an AfterInstall hooks script to be able to get the git commit SHA (GUI: "Commit ID") so it can be put into a file on the server.  This would save me having to tell our developers "Just use the GUI" to find out what code is actively on the box (and yes I'm well aware the agent has this information deep within /opt/codedeploy-agent).  An environment variable would be absolutely perfect.

**Comment by elijahchancey** [comment]
I have the exact same issue and workaround as woodhull. Querying the deployment ID to get the commit id. +1 for this feature request!

**Comment by gergnz** [comment]
+1

**Comment by piercus** [comment]
+1

**Comment by fabiopaiva-praxis** [comment]
+1

**Comment by joncon** [comment]
+1

**Comment by jcramb** [comment]
+1

**Comment by shogochiai** [comment]
+1

**Comment by RAR** [comment]
+1

**Comment by richardowen** [comment]
+1

**Comment by dilip-grexit** [comment]
+1

**Comment by apoorv-kumar** [comment]
+1

**Comment by apoorv-kumar** [comment]
+1

**Comment by apoorv-kumar** [comment]
I think this solves it - https://forums.aws.amazon.com/thread.jspa?threadID=226646

**Comment by sebastianreloaded** [comment]
@apoorv-kumar it doesn't, as far as i understand, the linked thread is about codepipeline and not plain codedeploy

**Comment by annamataws** [comment]
Added to our task list so we can review this new design decision with the team

**Comment by mpdude** [comment]
I also have a use case that would benefit.

As a workaround, is it possible to query the commit ID through the API (using the AWS CLI, possibly)?

**Comment by dicato** [comment]
👍 on this request.

As others have noted, the workaround is to use the `DEPLOYMENT_ID` environment variable to query for the commit ID.

For example:
```
aws deploy get-deployment --deployment-id $DEPLOYMENT_ID  --query "deploymentInfo.revision.gitHubLocation.commitId" --output text 
```

**Comment by mwjones-aws** [comment]
This feature has been added as part of the 1.4.0 release.

**Comment by mpdude** [comment]
The 1.4.0 release exposes the commit SHA-1, but does not (yet) provide the repository URL itself for/from which die deployment was triggered. However, that information can be queried through the API when needed.

```
aws deploy get-deployment --deployment-id $DEPLOYMENT_ID  --query  ".deploymentInfo.revision.gitHubLocation.repository" --output text 
```
