### ISSUE TITLE
Allow to configure ARCHIVES_TO_RETAIN

### ISSUE THREAD

**Issue by Poil** [aws/aws-codedeploy-agent#37]
Hi,

It'll be nice to add an option to the configuration file to set ARCHIVES_TO_RETAIN

On some project I have 20 applications, so I can have potentially 20*5* size of the app (100MB) on the filesystem 

Best regards

**Comment by Poil** [comment]
#38

**Comment by todwilli** [comment]
Hi,
This is now possible thanks to https://github.com/aws/aws-codedeploy-agent/commit/c53f7d779d846654f0f48096e5f6bc602633622f

**Comment by suryanarayanan** [comment]
Fixed in https://github.com/aws/aws-codedeploy-agent/commit/ec9a73b0ee98a0b19418f4c6a0fe9026fe8b89dc  This will be out in the next agent release.
Thanks.
