### ISSUE TITLE
Version tracking file either does not exist or cannot be read in /data/codedeploy-agent/.version.

### ISSUE THREAD

**Issue by Poil** [aws/aws-codedeploy-agent#41]
Hi,

If you change ":root_dir:", version 1.0-1.854 of codedeploy is looking for ".version" in the :root_dir:, but this file stays in /opt/codedeploy-agent/.version

Best regards

**Comment by suryanarayanan** [comment]
Hi,
Thanks for reporting. Version tracking is best effort only. Being said that I do feel like we should fall back to default /opt/codedeploy-agent in case the agent couldn't find the version file under root_dir.
Thanks,
Surya.

**Comment by suryanarayanan** [comment]
Fixed in https://github.com/aws/aws-codedeploy-agent/commit/7cc004e5eef19b38434e5773a612b57be1cf43ad#diff-bd9cd66d816ad49fc7a72f3ec9d59cda
