### ISSUE TITLE
Updating the agent should not start the agent if it's not running

### ISSUE THREAD

**Issue by eric-tucker** [aws/aws-codedeploy-agent#45]
Follow-up to #43 (which I believe no one is reading).

I'm fine with auto updating the agent as long as the update process does not start the agent daemon.  There are scenarios where we want to honour chkconfig and not start the agent at boot.

Either the update process should not start the agent (restart is OK since it's obviously already running) or we shouldn't have a cron entry that runs at reboot to update the agent (since we already update every hour).

**Comment by vladgh** [comment]
I also agree with this issue.

As per this article https://blogs.aws.amazon.com/application-management/post/Tx1NRS217K1YOPJ/Under-the-Hood-AWS-CodeDeploy-and-Auto-Scaling-Integration

> If you prefer baking the agent into the base AMI, we recommend that you keep the agent service in a stopped state and use the launch scripts to start the agent service.

**Comment by eric-tucker** [comment]
Good find @vladgh .  The fact that AWS best practices cannot even be followed because of incorrect implementation starting a service without warning and ignoring chkconfig is very disappointing.

**Comment by feverLu** [comment]
This issue is fix with the latest host agent release: https://github.com/aws/aws-codedeploy-agent/releases/tag/v1.0-950
