### ISSUE TITLE
CodeDeploy does not report time or target of previous deployments.

### ISSUE THREAD

**Issue by jdrago999** [aws/aws-codedeploy-agent#47]
This screenshot says it all.

AWS: get your act together or pull CodeDeploy. This half-assed in-between thing is ridiculous.

<img width="902" alt="screen shot 2016-01-19 at 10 44 21 am" src="https://cloud.githubusercontent.com/assets/37591/12428633/9533f902-be9a-11e5-890e-77eab2306184.png">

**Comment by suryanarayanan** [comment]
Hi,
Can you tell us the steps to reproduce the above issue? I couldn't reproduce the above in my personal account. Also can you PM me or open a case with the account, application and deployment group to which you've deployed the above revision successfully?
Thanks,
Surya.

**Comment by feverLu** [comment]
Also, the Deployment Groups Deployed To column will be null if the revision doesn't have a successful deployment.

Thanks,
Binbin

**Comment by jdrago999** [comment]
Ah after using CodeDeploy for over a year, I finally see that "Revisions" are different than "Deployments" - as described here: https://medium.com/@devstack/usability-wishlist-for-amazon-web-services-8672860ee5c#.iji0vt6nl

**Comment by feverLu** [comment]
Ah yeah, revision and deployment are quite different concept for CodeDeploy. You can also check these on our docs.
- A revision contains a version of the source files AWS CodeDeploy will deploy to your instances or scripts CodeDeploy will run on your instances, including a appspec.file.
- Deployment is the actual process to deploy the revision.

I've read your blog link, especially for the CodeDeploy part. For example the search function for deployments, it's really to the point, and it is on our to do list. We really want to make the product better and better, and this is the reason that we are struggling everyday.

Thanks,
Binbin

**Comment by jdrago999** [comment]
@feverLu thanks - I look forward to the improvements.
