### ISSUE TITLE
Provide a way to specify target revision to deploy

### ISSUE THREAD

**Issue by antonbabenko** [aws/aws-codedeploy-agent#54]
The initial problem I have is that there seems to be no way to manage target revisions (eg, "promote as target revision") through CLI. Correct me if I am wrong?

---

It would be great if there is a way to specify which revision agent should deploy.

It is not always best idea to deploy "latest successfully deployed", because DB may have changed, or when doing debugging, or when scripts used for deployment are not idempotent (on purpose).

I can think of specific env like `AWS_DEPLOY_S3_LOCATION="bucket=BucketName,key=123.zip,bundleType=zip"` which can be used during deployment, if not empty.

**Comment by Jmcfar** [comment]
Hi,

Currently the target revision is the last successful deployment to the deployment group. We do not have a way to manually update the target revision without triggering a full deployment to the current fleet.  I have passed the feature request to the team for further review and consideration. Your feedback is very much appreciated!

**Comment by droidlabour** [comment]
Any update on this?

**Comment by droidlabour** [comment]
For my use case, I wanted AWS CodeDeploy to always deploy the latest changes.
https://github.com/PriceBoardIn/aws-codedeploy-agent/commit/6ea2d620d1c6100805ac04f7560a4d46c9ac01e5

So in order to specify a target revision. I think you can change the `commit` variable to point to a specific commit.

**Comment by imtutta** [comment]
+1 it would be very useful to be able to change the target revision.

For my use case, I hotfix the runtime environment without restarting the application, but I want that next autoscaling/deployment operations point to the correct revision to deploy.

**Comment by tterrace** [comment]
Chiming in to support this. When you have 10+ deployment groups under a new application it's annoying to have to "prime" the target revision for each deployment group by deploying to a single instance. It would be great to have an api call like `aws deploy mark-target-revision --application <...> --deployment-group <...> --s3-location <...>`
