### ISSUE TITLE
Add Support for Ubuntu 15.10 (wily) / Ruby 2.1

### ISSUE THREAD

**Issue by colinbjohnson** [aws/aws-codedeploy-agent#58]
It would be nice to be able to run AWS CodeDeploy on Ubuntu 15.10 (wily) which does not ship with Ruby version 2.0.

There are two workarounds I've listed below:
- add trusty repository to Ubuntu and install package Ruby2.0
- use RVM

In the case of Ubuntu, I have a preference for being able to run under the system provided, current version of Ruby.

**Comment by n1tr0g** [comment]
I had a quick look at the source code, but so far I can't find any reason why this should not work on ruby 2.3 except for hardcoded ruby2.0 path ... 

I will try to dig more ...

**Comment by madebydavid** [comment]
Hi, I am also experiencing this issue.

I symlinked the ruby binary like so: `sudo ln -s /usr/bin/ruby /usr/bin/ruby2.0`

However, the install stalls further along:
```
...
I, [2016-06-16T12:12:49.985181 #6701]  INFO -- : Running version No running version
I, [2016-06-16T12:12:49.985299 #6701]  INFO -- : Downloading version file from bucket aws-codedeploy-us-east-1 and key latest/VERSION...
I, [2016-06-16T12:12:50.022712 #6701]  INFO -- : Downloading version file from bucket aws-codedeploy-us-east-1 and key latest/VERSION...
I, [2016-06-16T12:12:50.037214 #6701]  INFO -- : Downloading package from bucket aws-codedeploy-us-east-1 and key releases/codedeploy-agent_1.0-1.966_all.deb...
I, [2016-06-16T12:12:50.136962 #6701]  INFO -- : Executing `/usr/bin/gdebi -n -o Dpkg::Options::=--force-confdef -o Dkpg::Options::=--force-confold /tmp/codedeploy-agent_1.0-1.966_all.tmp-20160616-6701-1kmvu7w.deb`...
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: ruby2.0
```

Managed to install it with a PPA:
```
sudo apt-get install software-properties-common
sudo apt-add-repository ppa:brightbox/ruby-ng
sudo apt-get update
sudo apt-get install ruby2.0
```

I agree, it would be nice if it worked with 15.10 out-of-the-box.

**Comment by Jmcfar** [comment]
Hi, we're tracking the work to update this on https://github.com/aws/aws-codedeploy-agent/issues/61, which should unblock the agent on both Ubuntu 15 and 16.
