### ISSUE TITLE
Ruby 2.0 is unmaintained - also cannot install on Ubuntu LTS

### ISSUE THREAD

**Issue by mhart** [aws/aws-codedeploy-agent#61]
The specific requirement for "ruby2.0" means that CodeDeploy cannot be installed on Ubuntu 16.04 LTS.

Considering that maintenance for Ruby 2.0 ended in February 2016, CodeDeploy is now relying on an unmaintained version. It was [advised well over a year ago](https://www.ruby-lang.org/en/news/2015/02/25/ruby-2-0-0-p643-is-released/) to move all Ruby 2.0 projects to a newer version.

This also means that the [CodeDeploy install instructions](http://docs.aws.amazon.com/codedeploy/latest/userguide/how-to-run-agent.html#how-to-run-agent-install-ubuntu) no longer work for Ubuntu as they say they should.

How should users who are on Ubuntu LTS install the CodeDeploy agent?

Is CodeDeploy still going to be maintained going forward? (Ruby 2.0 is over three years old now!)

**Comment by mhart** [comment]
Btw, I've tried manually compiling Ruby 2.0, using rvm, all to no avail – the CodeDeploy agent install script insists on a "ruby2.0" package being available and will not accept the manually installed version

**Comment by Raniz85** [comment]
You can work around this by installing Ruby 2.0 from the [Brightbox Ruby NG PPA](https://launchpad.net/~brightbox/+archive/ubuntu/ruby-ng)

Right now they don't have a PPA for 16.04 so you'll have to add the PPA for 15.10 but that ruby package currently installs without issue on 16.04.

```
sudo mkdir -p /etc/apt/sources.list.d
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C3173AA6
cat <<EOF | sudo tee /etc/apt/sources.list.d/brightbox-ubuntu-ruby-ng-wily.list
deb http://ppa.launchpad.net/brightbox/ruby-ng/ubuntu wily main
EOF
sudo apt-get update
sudo apt-get install ruby2.0
```

```
ubuntu@ip-10-0-100-238:~$ uname -a
Linux ip-10-0-100-238 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@ip-10-0-100-238:~$ cat /etc/issue
Ubuntu 16.04 LTS \n \l

ubuntu@ip-10-0-100-238:~$ sudo mkdir -p /etc/apt/sources.list.d
ubuntu@ip-10-0-100-238:~$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C3173AA6
Executing: /tmp/tmp.JcqFJKRTKy/gpg.1.sh --keyserver
keyserver.ubuntu.com
--recv-keys
C3173AA6
gpg: requesting key C3173AA6 from hkp server keyserver.ubuntu.com
gpg: key C3173AA6: public key "Launchpad PPA for Brightbox" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
ubuntu@ip-10-0-100-238:~$ cat <<EOF | sudo tee /etc/apt/sources.list.d/brightbox-ubuntu-ruby-ng-wily.list
> deb http://ppa.launchpad.net/brightbox/ruby-ng/ubuntu wily main
> EOF
deb http://ppa.launchpad.net/brightbox/ruby-ng/ubuntu wily main
ubuntu@ip-10-0-100-238:~$ sudo apt-get update
Hit:1 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease [94.5 kB]
Hit:3 http://security.ubuntu.com/ubuntu xenial-security InRelease                                                                    
Hit:4 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease                                                      
Get:5 http://ppa.launchpad.net/brightbox/ruby-ng/ubuntu wily InRelease [15.4 kB]                   
Get:6 http://ppa.launchpad.net/brightbox/ruby-ng/ubuntu wily/main amd64 Packages [3,764 B]
Get:7 http://ppa.launchpad.net/brightbox/ruby-ng/ubuntu wily/main Translation-en [1,764 B]
Fetched 115 kB in 0s (304 kB/s)  
Reading package lists... Done
ubuntu@ip-10-0-100-238:~$ sudo apt-get install ruby2.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libruby2.0
The following NEW packages will be installed:
  libruby2.0 ruby2.0
0 upgraded, 2 newly installed, 0 to remove and 4 not upgraded.
Need to get 0 B/2,882 kB of archives.
After this operation, 13.6 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Selecting previously unselected package ruby2.0.
(Reading database ... 53602 files and directories currently installed.)
Preparing to unpack .../ruby2.0_2.0.0.648-2bbox1~wily2_amd64.deb ...
Unpacking ruby2.0 (2.0.0.648-2bbox1~wily2) ...
Selecting previously unselected package libruby2.0:amd64.
Preparing to unpack .../libruby2.0_2.0.0.648-2bbox1~wily2_amd64.deb ...
Unpacking libruby2.0:amd64 (2.0.0.648-2bbox1~wily2) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up libruby2.0:amd64 (2.0.0.648-2bbox1~wily2) ...
Setting up ruby2.0 (2.0.0.648-2bbox1~wily2) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
ubuntu@ip-10-0-100-238:~$ ruby -v
ruby 2.0.0p648 (2015-12-16 revision 53162) [x86_64-linux-gnu]
```

**Comment by mhart** [comment]
@Raniz85 great, thanks for the instructions on how to do this – these should definitely be added to the [official documentation](http://docs.aws.amazon.com/codedeploy/latest/userguide/how-to-run-agent.html#how-to-run-agent-install-ubuntu)

I was using brightbox earlier on 15.10, but had issues adding the repo on 16.04 – glad it works by adding it manually

In any case, if AWS have any investment in CodeDeploy going forward they should definitely move off ruby2.0. I'd really like to see an official comment on this.

**Comment by pdalinis** [comment]
👍  we really need an update to this.

**Comment by vasanthperiyasamy** [comment]
+1

**Comment by ipsq** [comment]
+1

**Comment by 9sparkfuls** [comment]
+1

**Comment by n1tr0g** [comment]
+1 :)

**Comment by tsloughter** [comment]
Is it the case that it actually works fine on ruby 2.3? There is a PR that has been open for 11 days that simply changes what version the agent checks for: https://github.com/aws/aws-codedeploy-agent/pull/62

**Comment by feverLu** [comment]
We are actually actively working on relaxing the hard dependency on ruby2.0 now. Next release of the host agent should work with ruby versions >= 2.0

**Comment by n1tr0g** [comment]
I couldn't find any technical reason why this agent shouldn't work on ruby 2.3, except for the hardcoded version in the scripts :)

**Comment by bdashrad** [comment]
The commit cfbebaf by @feverLu last night fixes the installer, but not the deb package that it downloads. We're partway there.

**Comment by bdashrad** [comment]
I forked this and am now building a deb package with fpm for our use until the office version supports ruby > 2.0.

https://github.com/bdashrad/aws-codedeploy-agent

**Comment by timurb** [comment]
Guys, you just read the banner which is displayed on installation and do something like `sudo ln -s /usr/bin/ruby /usr/bin/ruby2.0` before installing the package.

This worked for me perfectly.
I've used:
* CentOS 7
* self-built Ruby 2.2 (installed somewhere to `/opt`)
* CodeDeploy RPM package from `aws-codedeploy-us-east-1` S3 bucket

**Comment by n1tr0g** [comment]
@timurb this won't work on ubuntu since the deb package requires ruby2.0 to be installed.

**Comment by timurb** [comment]
@n1tr0g is that really dependency or simple checking for `/usr/bin/ruby2.0` done in postinst script?

in CentOS that's postinst script

**Comment by n1tr0g** [comment]
@timurb it's a package dependency in Ubuntu ....

**Comment by runningman84** [comment]
Any news here?

**Comment by tsloughter** [comment]
Yea, it has been a month since the last update. Is there any news on when the latest ubuntu lts will be supported and the unmaintained version of ruby will not longer be required?

**Comment by nhumphreys** [comment]
+1

**Comment by stevenjack** [comment]
Had a nice few hours messing around with this, ended up using @Raniz85 solution..

Might have been worth thinking about writing the agent in something a bit more portable like go..

**Comment by emirb** [comment]
After Ruby 2.0 installation, codedeploy agent still can't be installed on Debian 8 (Jessie).

+1

**Comment by runningman84** [comment]
Everybody should talk to his TAM and request an update.

**Comment by vikash** [comment]
+1

**Comment by 9sparkfuls** [comment]
RE TAM, good idea. I just sent a note.

**Comment by emirb** [comment]
TAM?

**Comment by arojeff** [comment]
sudo add-apt-repository ppa:brightbox/ruby-ng
sudo apt-get update
sudo apt-get install ruby2.0

**Comment by abh1nav** [comment]
@feverLu any updates here? CodeDeploy Agent installs are still failing on 16.04 instances because of the hard requirement on ruby2.0.

**Comment by mhart** [comment]
@arojeff oh ok, so they have a PPA for 16.04 now? That must have changed recently: https://github.com/aws/aws-codedeploy-agent/issues/61#issuecomment-218378401

**Comment by arojeff** [comment]
@mhart - Yes, that worked for me!

**Comment by j88per** [comment]
Kinda stunned that here it is September and AWS still hasn't fixed this and we have to work around it.  C'mon Amazon get your shit in gear.

**Comment by jackdpeterson** [comment]
In the interest of the rest of the community here, I'm going to post a slighty redacted AWS premium support conversation that should prove to be useful for most folks and help keep the hordes at bay until AWS devs can resolve some issues before code deploy is good to go.

```Thanks for contacting AWS Premium Support. My name is [REDACTED] and I'll be providing support for you today. From your response, I understand that you want to deploy our AWS CodeDeploy agent on the Linux OS "Ubuntu 16.04' release. 

Unfortunately, at the moment, our AWS CodeDeploy agent is not tested and supported on the Ubuntu operating system version 16.04. We released CodeDeploy agent version 1.0.1.1011 to enable support for all versions of Ruby 2.x in the AWS CodeDeploy agent and the AWS CodeDeploy agent updater, has now been rolled back to previous version 1.0.1.998 due to some other issues in the latest revision. 

---  [1]http://docs.aws.amazon.com/codedeploy/latest/userguide/host-cleanup.html 

Our code deploy service team is working on the latest release, as of now our team has planned tentatively to release the latest version by the end of [Specific date redacted] 2016 as it has got some internal dependencies and other existing issues that need to be addressed. 


However, we value your interest, and have come up with possible workaround in order to make our Code Deploy agent in order to support on the OS Ubuntu 16.04 using the latest latest ruby 2.3 package. 

Please follow the below given steps as root to setup your Code Deploy agent on Ubuntu 16.04. 

1) Refresh the apt-get repository #apt-get update 

2) Install python pip #apt-get install python-pip -y 

3) Refresh the apt-get repository #apt-get update 

4) Install the Ruby 2.3 package #apt-get install ruby2.3 -y To check the ruby version #ruby -v 

5) Install Wget package. #apt-get install wget -y 

6) Refresh the apt-get repository #apt-get update 

7) Download the supported Code Deploy agent from our S3 repository. #wget https://aws-codedeploy-ap-southeast-2.s3.amazonaws.com/latest/codedeploy-agent_all.deb 

Note: aws-codedeploy-ap-southeast-2 is the bucket name that I have used for ap-southeast-2 sydney region To find the specific code deploy bucket name for specific region, please refer the below documentation link. http://docs.aws.amazon.com/codedeploy/latest/userguide/how-to-run-agent-install.html#how-to-run-agent-install-ubuntu 

8) Install the Code Deploy agent #dpkg --force-all -i ./codedeploy-agent_all.deb 

9) Find the ruby binary path. #which ruby 

10) Create a soft link to refer the latest ruby (2.3 version ) as ruby 2.0 #ln -s /usr/bin/ruby /usr/bin/ruby2.0 #ls -ltr /usr/bin/ruby2.0 

11) Start and check the Code Deploy agent process. #service codedeploy-agent start #service codedeploy-agent status 

12 ) To start the Code Deploy agent across reboot #update-rc.d codedeploy-agent defaults Note: I have tested the above work around on my test environment with few deployments without any issues. Please test the same steps on your test environment before proceeding onto your production environment. I hope the above helps. Please let me know if you have any questions or concerns or if there is anything else I can do for you. Best 

regards, 

[redacted]```

**Comment by ambareesha** [comment]
Folks, we are working on fixing the Ruby 2.0 dependency issue. We released agent version 1.0.1.1011 which was the first step to fixing the problem, but we had to roll it back due to some issues we discovered. We are trying to address the issues and test the agent thoroughly before the next release, which should roll out in a couple of weeks.

**Comment by TheBenMay** [comment]
@arojeff This has worked for the Ubuntu 16.04 Marketplace AMI and the new AMI in the quick launch.

**Comment by klatu201** [comment]
Come on  AWS, fix this....
 I had this issue with the vanilla vagrant ubuntu box -  hashicorp/precise64 

Workaround: 
sudo apt-get install software-properties-common python-software-properties
sudo add-apt-repository ppa:brightbox/ruby-ng-experimental
sudo apt-get update
sudo apt-get install ruby2.0

**Comment by apenney** [comment]
@ambareesha How many more weeks is this likely to take?  No offense, but this is pretty awful.

**Comment by ambareesha** [comment]
@apenney, we are in the process of rolling out the first set of changes this week (a couple of big regions done and some more to go). This set of changes will upgrade the preinstalled agent to using Ruby2.x. Once that goes through, we will release the updated installers. I'm expecting it to be a few more weeks before you can install on Ruby2.x. Thanks for your patience!

In the meantime, have you tried @klatu201's workaround? That should unblock you for the moment.

**Comment by gtangquri** [comment]
following @klatu201 's workaround and then continuing with AWS' docs works

**Comment by ambareesha** [comment]
We have released host agent version 1.1037 which gets us halfway through the Ruby2.x migration process. The current agent invokes the latest version of ruby installed on the system.

Next steps:
Update the ruby dependency in the rpm and deb installers. The install script will also be updated.
We are actively working on rolling out these changes.

**Comment by whtevn** [comment]
in the meantime, is there any way to just give us a flag that will run the right interpreter. I have RVM installed with ruby 2.0 available. If I could just point this script at that, I would not need to make a dummy ruby 2.0 package on my production machine just to install this logging agent.

**Comment by octaviandavid** [comment]
+1

**Comment by ambareesha** [comment]
Thank you all for your patience.
We released the host agent version 1.1045 a couple of weeks ago which works with ruby2.3 on Ubuntu 16. We hope this resolves your issue. Please let us know if you still face any problems.

**Comment by mhart** [comment]
Confirmed that the steps outlined in the docs now work for Ubuntu 16.04 (in `us-east-1`, on `ami-40d28157`): http://docs.aws.amazon.com/codedeploy/latest/userguide/how-to-run-agent-install.html#how-to-run-agent-install-ubuntu

The description of the messages from `service` isn't correct though. After install, the message looks like this:

```console
$ sudo service codedeploy-agent status
● codedeploy-agent.service - LSB: AWS CodeDeploy Host Agent
   Loaded: loaded (/etc/init.d/codedeploy-agent; bad; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:systemd-sysv-generator(8)
```

Then after `sudo service codedeploy-agent start`, the message looks like this:

```console
$ sudo service codedeploy-agent status
● codedeploy-agent.service - LSB: AWS CodeDeploy Host Agent
   Loaded: loaded (/etc/init.d/codedeploy-agent; bad; vendor preset: enabled)
   Active: active (exited) since Sat 2016-11-26 16:16:28 UTC; 20s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 9082 ExecStart=/etc/init.d/codedeploy-agent start (code=exited, status=0/SUCCESS)

Nov 26 16:16:28 ip-172-31-30-252 systemd[1]: Starting LSB: AWS CodeDeploy Host Agent...
Nov 26 16:16:28 ip-172-31-30-252 codedeploy-agent[9082]: Starting codedeploy-agent:
Nov 26 16:16:28 ip-172-31-30-252 systemd[1]: Started LSB: AWS CodeDeploy Host Agent.
```

Anyway, closing this for now – if others have problems getting this running, probably best to open separate issues – the main concern has been addressed. Thanks all!

**Comment by martinb3** [comment]
It seems that the documentation still states 16.04 isn't supported; it would be good to update that as well, if someone can: http://docs.aws.amazon.com/codedeploy/latest/userguide/host-cleanup.html#how-to-run-agent-supported-oses

**Comment by sc-pulsion** [comment]
Hi I am seeing this issue on eu-west-2. It looks like the agent deb file is not up to date (1.0-1.1011.1). Can you also update that region please?

```
I, [2016-12-22T10:54:50.804562 #28973]  INFO -- : Starting Ruby version check.
I, [2016-12-22T10:54:50.804725 #28973]  INFO -- : Starting update check.
I, [2016-12-22T10:54:50.804825 #28973]  INFO -- : Attempting to automatically detect supported package manager type for system...
I, [2016-12-22T10:54:50.809638 #28973]  INFO -- : Checking AWS_REGION environment variable for region information...
I, [2016-12-22T10:54:50.809740 #28973]  INFO -- : Checking EC2 metadata service for region information...
dpkg-query: package 'codedeploy-agent' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
I, [2016-12-22T10:54:50.837469 #28973]  INFO -- : Running version No running version
I, [2016-12-22T10:54:50.837598 #28973]  INFO -- : Downloading version file from bucket aws-codedeploy-eu-west-2 and key latest/VERSION...
I, [2016-12-22T10:54:50.856689 #28973]  INFO -- : Downloading version file from bucket aws-codedeploy-eu-west-2 and key latest/VERSION...
I, [2016-12-22T10:54:50.873736 #28973]  INFO -- : Downloading package from bucket aws-codedeploy-eu-west-2 and key releases/codedeploy-agent_1.0-1.1011.1_all.deb...
I, [2016-12-22T10:54:50.924725 #28973]  INFO -- : Executing `/usr/bin/gdebi -n -o Dpkg::Options::=--force-confdef -o Dkpg::Options::=--force-confold /tmp/codedeploy-agent_1.0-1.1011.1_all.tmp-20161222-28973-1xhue2p.deb`...
Reading package lists... Done
Building dependency tree
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: ruby2.0
```

**Comment by ambareesha** [comment]
sc-pulsion@, we have uploaded the latest agent to eu-west-2
