### ISSUE TITLE
codedeploy-agent keeps a default of 11 and a minimum of 5 copies of my application on disk

### ISSUE THREAD

**Issue by timgilbert** [aws/aws-codedeploy-agent#64]
I have a few related issues here that are about how many copies of my application codedeploy-agent keeps around on disk.

With the default settings, codedeploy-agent will keep 11 copies of my application on disk after enough deployments happen:
- One actual installed, deployed application
- For each of the previous 5 revisions:
  - One copy of the `.tar` application revision from s3
  - One unpacked directory of that same application revision in the `deployment-archive` directory

This seems excessive. I'm deploying a 160MB jar file to an instance with 8GB of disk space, and codedeploy-agent is consuming 1.6GB of disk just to keep old revisions around.

I can moderate this somewhat by changing the `max_revisions` setting in `/etc/codedeploy-agent/conf/codedeployagent.yml` (although this feature is not documented anywhere, as far as I can tell). But thanks to #57, the lowest value I can set this to is 1, which winds up keeping 5 copies of my application on disk:
- One deployed copy of the application
- For the current and previous deployments, one bundle file and one unzipped directory

Some suggestions for how this could be improved:
- codedeploy-agent should keep either the unpacked `deployment-archive` or the application revision archive file file around, but not both - it should delete one or the other after a successful deployment.
- The default value of `max_revisions` should be set to 1 (which actually means two previous deployments)
- #57 should be fixed. ;)

**Comment by gaohan137** [comment]
Hi timgilbert,

max_revision is not documented anywhere? hmm -> http://docs.aws.amazon.com/codedeploy/latest/userguide/host-cleanup.html

The fix for #57 will be fixed in next release of the host agent.

**Comment by LPerezCBG** [comment]
Im having a issue where my deployment scrip is failing and i'm not sure why. When i use locate i can se that there are some files kept in the deployment-archive

/opt/codedeploy-agent/deployment-root/b0262369-...-4c44-ab6d-6ee70839a1ae/d-.../deployment-archive/deploy/scripts/ApplicationStop.sh
/opt/codedeploy-agent/deployment-root/b0262369-...-4c44-ab6d-6ee70839a1ae/d-.../deployment-archive/deploy/scripts/ApplicationStop.sh
/opt/codedeploy-agent/deployment-root/b0262369-...-4c44-ab6d-6ee70839a1ae/d-../deployment-archive/deploy/scripts/ApplicationStop.sh. 

And these are Old deployments (failed attempts). I believe i've fixed my scrip issue but i don't know how to make the codedeploy agent use the new scripts from GitHub and not try to pick up from the old deployments. is there like a deployment-archive cache clear or something for this ?

**Comment by webmutation** [comment]
I configured the :max_revisions: parameter to 3 and it continues to have 5 folders and going over the amount of space... currently the only thing that seems to work is to force the cleanup thru a hook.

Installed Packages
Name        : codedeploy-agent
Arch        : noarch
Version     : 1.0
Release     : 1.1352
Size        : 16 M
Repo        : installed
Summary     : Provides the required files for CodeDeploy agent to run in EC2 instances
License     : Amazon.com Internal
Description : CodeDeploy instance agent is responsible for doing the actual work of deploying software
            : on an EC2 instance.

**Comment by annamataws** [comment]
Hi,

The max_revisions works in the new agent releases and deletes the extra deployment revisions within a deployment group. It works when being set to an integer that is 1 or greater. If you have multiple deployment groups, each deployment group will honor the max_revisions separately. 

https://github.com/aws/aws-codedeploy-agent/blob/c3860f74c3fe06e4fe16dbfcb7389c64c0c339d4/lib/instance_agent/plugins/codedeploy/command_executor.rb#L77

Please let me know if you are still seeing problems.

Thank you

**Comment by annamataws** [comment]
Will close this since the fix has been out for a while.

**Comment by send2kbl** [comment]
@manikarnam 
Any updates or workaround on this issue ? 

Besides the same Log error from a previous deployment, I'm getting this error message on the console:
`The overall deployment failed because too many individual instances failed deployment, too few healthy instances are available for deployment, or some instances in your deployment group are experiencing problems.`

PS. I did restart the agent
