### ISSUE TITLE
rake test-integration fails:  Amazon Linux,  ruby 2.2.5p319

### ISSUE THREAD

**Issue by naul1** [aws/aws-codedeploy-agent#76]
rake test-integration
/usr/local/rvm/rubies/ruby-2.2.5/bin/ruby -S bundle exec cucumber features -t ~@Ignore
@codedeploy-agent
Feature: Deploy using AWS CodeDeploy Agent

Using keypair : codedeploy-agent-integ-test-key
  Scenario: Doing a sample deployment                                                              # features/agent.feature:5
    Given I have an application                                                                    # features/step_definitions.rb:46
      It is going to take a few minutes to spin up an ec2 instance...
    And I have a deployment group containing a single EC2 AMI with preinstalled new instance agent # features/step_definitions.rb:52
    When I create a deployment for the application and deployment group with the test S3 revision  # features/step_definitions.rb:61
    Then the overall deployment should eventually be in progress                                   # features/step_definitions.rb:76
    And the deployment should contain all the instances I tagged                                   # features/step_definitions.rb:80

    And the overall deployment should eventually succeed                                           # features/step_definitions.rb:85
      
      expected: "Succeeded"
           got: "Failed"
      
      (compared using ==)
       (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions.rb:231:in `block in assert_deployment_status'
      ./features/step_definitions.rb:20:in `eventually'
      ./features/step_definitions.rb:229:in `assert_deployment_status'
      ./features/step_definitions.rb:86:in `/^the overall deployment should eventually succeed$/'
      features/agent.feature:11:in `And the overall deployment should eventually succeed'

Failing Scenarios:
cucumber features/agent.feature:5 # Scenario: Doing a sample deployment

1 scenario (1 failed)
6 steps (1 failed, 5 passed)
6m5.668s

**Comment by Jmcfar** [comment]
Thanks for the bug report. This should now be fixed!
