### ISSUE TITLE
CodeDeployAgent auto update fails and leaves agent stopped

### ISSUE THREAD

**Issue by chriskinsman** [aws/aws-codedeploy-agent#77]
This leaves the machine in a state that it is unable to accept deployments.

Looking at the logs the issue appears to be that we have modified the codedeployagent.yml file to move the deployment root to a new volume.  This causes DPKG to hang waiting for input asking if it should overwrite or keep the old one.

From the logs:

Setting up codedeploy-agent (1.0-1.1011) ... 
Configuration file '/etc/codedeploy-agent/conf/codedeployagent.yml' ==> Modified (by you or by a script) since installation. ==> Package distributor has shipped an updated version. What would you like to do about it ? Your options are: Y or I : install the package maintainer's version N or O : keep your currently-installed version D : show the differences between the versions Z : start a shell to examine the situation The default action is to keep your current version.
**\* codedeployagent.yml (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package codedeploy-agent (--install): EOF on stdin at conffile prompt
Processing triggers for ureadahead (0.100.0-16) ...
Errors were encountered while processing: codedeploy-agent   Building data structures... Done
E, [2016-08-17T18:33:19.042768 #8006] ERROR -- : Error installing /tmp/codedeploy-agent_1.0-1.1011_all.tmp-20160817-8006-d6ku3a.deb.
I, [2016-08-17T19:33:01.651283 

After this failure the old agent is not restarted.  This is a huge issue.  Please advise how to correct.

**Comment by gdeblina** [comment]
This issue should be resolved with the latest host agent version. Please let us know if you are still facing this issue.
