### ISSUE TITLE
Get more logs from the agent

### ISSUE THREAD

**Issue by ys** [aws/aws-codedeploy-agent#8]
It is limited to 2048 for now.

I see all my ruby traces truncated... Would be cool to save the whole log somewhere on disk and just point to it too.

Or return more information to the server.

**Comment by todwilli** [comment]
The whole log is saved on the disc in the deployment directory under logs/scripts.log
On Linux based systems it defaults to  '/opt/codedeploy-agent/deployment-root/<DEPLOYMENT-GROUP-ID>/<DEPLOYMENT-ID>/logs/scripts.log'
On Windows systems the default is 'C:\ProgramData\Amazon\CodeDeploy\<DEPLOYMENT-GROUP-ID>\<DEPLOYMENT-ID>\logs\scripts.log'
