### ISSUE TITLE
Getting Code Deploy On Prem Working with Windows 10 Home

### ISSUE THREAD

**Issue by taylortdixon** [aws/aws-codedeploy-agent#81]
Trying to get CodeDeploy working on one of the Intel Compute Sticks. Running Windows 10 Home. Has anybody else successfully gotten the on-prem codedeploy agent running on Windows 10?

Receiving the following error when running (as administrator): 

> Action start 14:31:01: PublishFeatures.

> Action ended 14:31:01: PublishFeatures. Return value 1.
> Action start 14:31:01: PublishProduct.
> Action ended 14:31:01: PublishProduct. Return value 1.
> Action start 14:31:01: InstallFinalize.
> Info 1923.Service 'CodeDeploy Host Agent Service' (codedeployagent) could not be installed.  Verify that you have sufficient privileges to install system services.
> MSI (s) (74:38) [14:31:03:383]: Product: CodeDeploy Host Agent -- Error 1939. Service 'CodeDeploy Host Agent Service' (codedeployagent) could not be configured.  This could be a problem with the package or your permissions. Verify that you have sufficient privileges to configure system services.
> Error 1939. Service 'CodeDeploy Host Agent Service' (codedeployagent) could not be configured.  This could be a problem with the package or your permissions. Verify that you have sufficient privileges to configure system services.
> Action ended 14:31:03: InstallFinalize. Return value 3.
> Action ended 14:31:03: INSTALL. Return value 3.
> MSI (s) (74:38) [14:31:03:461]: Product: CodeDeploy Host Agent -- Installation failed.
> MSI (s) (74:38) [14:31:03:461]: Windows Installer installed the product. Product Name: CodeDeploy Host Agent. Product Version: 1.0.1.998. Product Language: 1033. Manufacturer: Amazon Web Services. Installation success or error status: 1603.
> === Logging stopped: 9/27/2016  14:31:03 ===

**Comment by feverLu** [comment]
Can you also provide the AMI that we can dig into?

**Comment by taylortdixon** [comment]
feverLu - reminder this is an on-premises issue, no AMI for it.

**Comment by feverLu** [comment]
My bad. Does reinstall solve the problem? We have a known issue on Windows 10 that the installer failed to update the service configuration, which cause the installation to fail.

**Comment by taylortdixon** [comment]
So I discovered that Windows Defender was blocking the install of the codedeploy-agent (silently). One I added an exception, it installed and deployed successfully.  

We can close this ticket. Thanks.
