### ISSUE TITLE
Agent can't untar bundle in Ubuntu 16.04

### ISSUE THREAD

**Issue by jonathlela** [aws/aws-codedeploy-agent#84]
Hi,

In Ubuntu 16.04, deployments fail with the following error :

`2016-11-08T10:00:12 ERROR [codedeploy-agent(16261)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Error during perform: RuntimeError - Error extracting tar archive: 127 - /opt/codedeploy-agent/lib/instance_agent/platform/linux_util.rb:77:in `execute_tar_command'
`

By looking to linux_util.rb, the command to be run is

` pushd #{dest} && /bin/tar -zxpsf #{bundle_file} && popd`

It's then evaluated with the bakcquotes mechanism.

As far as I understand ruby, it's hardcoded that this command is evaluated with /bin/sh. However, in Ubuntu 16.04, /bin/sh is linked with /bind/dash by default, pushd/popd is a bashism that does not exist in dash, hence the 127 error code.

I have linked /bin/sh to /bin/bash, and codedeploys then works as intended.

I think the command should not refer to pushd and popd, and the script should use 'Dir.chdir' instead.

Thanks,

Jonathan

NB: Thes push/popd mechanism has been recently added in https://github.com/aws/aws-codedeploy-agent/commit/c4cf46195ca4cc59749adb6ca1b8fedadf5aa80f

**Comment by ambareesha** [comment]
Thanks for bringing this to our notice. We have reverted the change to use pushd and popd.
