### ISSUE TITLE
Package installs init script and systemd unit

### ISSUE THREAD

**Issue by FlorianHeigl** [aws/aws-codedeploy-agent#87]
In Centos7:
I found that I have both the init script and the unit file installed.
There should only be the systemd unit.

This is the version of the package I used to install:

```
[me~]$ rpm -qip codedeploy-agent.noarch.rpm 
Name        : codedeploy-agent             Relocations: (not relocatable)
Version     : 1.0                               Vendor: Amazon.com
Release     : 1.1037                        Build Date: Sat 01 Oct 2016 09:30:32 PM CEST
Install Date: (not installed)               Build Host: sds-tod-workers-2b-m4l-i-0dec1ecb.us-west-2.amazon.com
Group       : Applications/System           Source RPM: codedeploy-agent-1.0-1.1037.src.rpm
Size        : 9897339                          License: Amazon.com Internal
Signature   : (none)
Summary     : Provides the required files for CodeDeploy agent to run in EC2 instances
Description :
CodeDeploy instance agent is responsible for doing the actual work of deploying software
on an EC2 instance.
```

**Comment by gdeblina** [comment]
Are you running into any issue trying to deploy using the code deploy agent?

**Comment by annamataws** [comment]
Hi,

Are you having any problems with CodeDeploy that you'd like us to still look into with you?

**Comment by FlorianHeigl** [comment]
hi, that was over a year ago, and you didn't ever try it out but flagged this as "waiting for input".
i don't care if your software works, feel free to close it.

**Comment by annamataws** [comment]
Sorry for the late response. We are working on this duplicate issue https://github.com/aws/aws-codedeploy-agent/issues/130.
