### ISSUE TITLE
cannot use pm2 with condedeploy

### ISSUE THREAD

**Issue by Ethanjfobrien** [aws/aws-codedeploy-agent#89]
it appears that codedeploy cannot be used for applications that run under pm2

failing script:
#!/bin/bash -i
pm2 reset all -s
pm2 restart all -s

log tail:
LifecycleEvent - ApplicationStart
Script - deploy/applicationstart.sh
[stderr]bash: cannot set terminal process group (-1): Inappropriate ioctl for device
[stderr]bash: no job control in this shell

**Comment by mattlo** [comment]
@Ethanjfobrien FWIW, I'm using PM2 successfully on code deploy over 20+ instances. I had to modify the node_modules default directory (https://docs.npmjs.com/getting-started/fixing-npm-permissions option 2) to successfully communicate to PM2 with the default user (specified in appspec.yml)

```
OS Version
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
Node Version
v6.9.2
PM2 Version
2.2.1
```

**Comment by Ethanjfobrien** [comment]
What scripts are you running in your appspec? e.g. are you piping to /dev/null?

**Comment by annamataws** [comment]
The problem seems to have been mostly resolved. You may reopen the issue if more help is needed.

**Comment by jonathangaldino** [comment]
I think I need a little help.

I have this script:

#!/bin/bash -i
pm2 delete all
pm2 start main.js

When codedeploy runs the appspec, I have debugged this:

**ScriptFailed** :: _Message_: MScript at specified location: scripts/application_start.sh run as user ubuntu failed with exit code 127

```
[stderr]/opt/codedeploy-agent/deployment-root/22bf6a92-6f35-495f-97f4-309e8c51ce5f/d-RBG2OP4H3/deployment-archive/scripts/application_start.sh: line 4: pm2: command not found
[stderr]/opt/codedeploy-agent/deployment-root/22bf6a92-6f35-495f-97f4-309e8c51ce5f/d-RBG2OP4H3/deployment-archive/scripts/application_start.sh: line 7: pm2: command not found
```

**Comment by vi4hu** [comment]
I was having this problem and the solution given here is not clear at all! tho I was able to figure out a simple fix.

Codedeploy runs with `root` permission and I can't change it as it's required to do other operations. Since my current pm2 process user is a different user let's say `ubuntu` I needed to change into that.

**Solution:**
```
# change
pm2 restart all
# to 
sudo -u ubuntu pm2 restart all
```
