### ISSUE TITLE
Gdebi-Core

### ISSUE THREAD

**Issue by vladgh** [aws/aws-codedeploy-agent#9]
The install scripts ensures `gdebi` on debian based system. However, this also installs a very large number of dependencies (105 MB). Wouldn't `gdebi-core` make more sense in a non-interactive environment? It's only 17.5 MB.

Ref: https://github.com/aws/aws-codedeploy-agent/blob/master/bin/install#L221

**Comment by suryanarayanan** [comment]
Hi,

Thanks for reporting this. We will look into this to check if gdebi-core is enough for agent deb installation.

Thanks,
Surya.

**Comment by vladgh** [comment]
Currently I manually install `gdebi-core` before I run the installer script for codedeploy. This way, the installer sees the `gdebi` executable and does not install it again.

**Comment by Pryz** [comment]
Why do we need gdebi instead of apt-get ?

**Comment by suryanarayanan** [comment]
We need gdebi to install a local .deb. apt-get doesn't have anything equivalent to 'yum localinstall'.

**Comment by vladgh** [comment]
Well, you are sort of right. There is `dpkg -i X.deb` on Debian based systems, but `gdebi` has the advantage of installing the `.deb` file and fetch all other dependencies from `apt` repositories. However, in this case, the only dependency specified in the deb file is `ruby2.0` which the `bin/install` script installs anyway before the deb.
In my bootstrap scripts I use simply:

```
sudo apt-get -qy install ruby2.0
wget -qO /tmp/codedeploy-agent_all.deb https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/codedeploy-agent_all.deb
sudo dpkg -i /tmp/codedeploy-agent_all.deb
```

**Comment by suryanarayanan** [comment]
Sure. you can do that. But it is safer to leave the dependency resolution to a package management system/installation tool rather than doing it manually. For e.g, your bootstrap script would break if the set of installer dependencies change in future.

**Comment by vladgh** [comment]
Absolutely, I agree. But this is just a temporary fix for myself, because I don't see the point installing the entire X Window System (X.Org) infrastructure, on which gdebi is dependent.
That's why I started this issue, the agent does not need `gdebi` but only `gdebi-core` which provides the required functionality, without the extras.

**Comment by suryanarayanan** [comment]
Replacing gdebi with gdebi-core is in our queue. The major part of that task is to make sure switching to gdebi-core does not break the agent installation in any of the supported versions of Ubuntu.
I'll post an update once I merge that change into master. Thanks.

**Comment by suryanarayanan** [comment]
Fixed in commit https://github.com/aws/aws-codedeploy-agent/commit/4d72f02aa7a19e435db938671cd82ca015da013f
