### ISSUE TITLE
Code deploy agent is sometimes taking too long to download the tarball.

### ISSUE THREAD

**Issue by apdewli** [aws/aws-codedeploy-agent#91]
We are using AWS codedeploy to deploy application in our ec2 based servers. Generally deployment runs ok. But we quite often observe issue that the agent not able to download the tarball for even after one hour and there is no error in logs. Please let us know  if anyone encountered this issues.

We are using private/corporate repository on github..

thanks and Regards,
anoop Prasad

**Comment by gaohan137** [comment]
Maybe try the deployment with the verbose flag turned on for the host agent: http://docs.aws.amazon.com/codedeploy/latest/userguide/agent-configuration-reference.html ?

This might offer some insight into what actually happened

**Comment by annamataws** [comment]
Hi,

Is this still a problem you'd like us to help with?

**Comment by annamataws** [comment]
We haven't received any response in about a year so we are closing this issue.
