### ISSUE TITLE
eu-west-2 Agent Version Incorrect (ruby2.0 error)

### ISSUE THREAD

**Issue by sc-pulsion** [aws/aws-codedeploy-agent#92]
The version of the agent pulled down from eu-west-2 is 1.0-1.1011.1 which still has the ruby2.0 dependency error. I see in this post https://github.com/aws/aws-codedeploy-agent/issues/61#issuecomment-263070062 stating that version 1.1045 was released. 

Please can you update the deb file? Thanks.

**Comment by ambareesha** [comment]
Thank you for bringing this to our notice. We had inadvertently uploaded the older version of the host agent when launching the region.

I have uploaded the latest versions of the installers to the s3 bucket now.

**Comment by sc-pulsion** [comment]
Thankyou
