### ISSUE TITLE
[ENHANCEMENT] Install script - Exeption handling and retrying when downloading version file/package

### ISSUE THREAD

**Issue by felipeamarante** [aws/aws-codedeploy-agent#95]
Hi Guys,

I have went trough the install script and seems that there is no exception handling for get_version_file_from_s3 and get_package_from_s3 executions. Hence is downloading a file externally, shouldn't be a good idea to have it retrying after in case of any exception happens?

Thanks!

**Comment by felipeamarante** [comment]
Closed by mistake.

**Comment by felipeamarante** [comment]
#142

**Comment by rohkat-aws** [comment]
@felipeamarante  pr merged ,closing the issue
