### ISSUE TITLE
agent doesn't find github repository

### ISSUE THREAD

**Issue by makkaba** [aws/aws-codedeploy-agent#97]
deploy was successful when i use private repository.
but, when i move repository into organization, 
deploy fails with an error "Not found" on Bundle Download stage.

i put this down (organization/reponame) when i try deploy.
is there another expression for organization address?

i tried other private repository, it works fine.
and all deploy through S3 bucket works well.

**Comment by makkaba** [comment]
i figured it out. 
github "organization" blocks 3rd party access to all repositories which belong to this organization by default.
because of this, codedeploy-agent generates a message "Not Found".
(even though i think "Access denied" is better message.. )
so you need to turn off this restriction on settings! :)
i think it would be better if you warn this situation on AWS guide. 
(sorry for bad english.)

**Comment by bmschwa** [comment]
Thanks a lot for the post.  the AWS documentation, but this would be a good thing for them to put in bold (I missed it too)
