### ISSUE TITLE
Allow * wildcard in source instruction of files section in appspec.yml

### ISSUE THREAD

**Issue by StanSvec** [aws/aws-codedeploy-agent#98]
I have the definition in appspec.yml:

```
files:
  - source: target/app-*.jar
    destination: /home/ec2-user/app/bin
```

However this causes the following error instead of copying all jar files matching the wildcard criteria:

> No such file or directory - /opt/codedeploy-agent/deployment-root/7f904e56-1745-4962-8a0b-6fc6faf54c5a/d-LUO0XZ3VJ/deployment-archive/target/app-*.jar

Thanks.

**Comment by feverLu** [comment]
We don't support wildcard for files names in the appspec file. As the doc describes: http://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref-files.html, either you can specify the whole folder or you may want to give the path of specific file.

Thanks,
Binbin

**Comment by StanSvec** [comment]
I sorted my problem by replacing the wildcard with the required value by using sed utility in the post-build shell execution action on Jenkins. Please feel free to close this ticket if you don't plan to implement this feature (I still believe it can be handy in some cases though).

Thanks,
Stan

**Comment by feverLu** [comment]
I'll forward the feature request to our product manager, thanks

**Comment by kennyk65** [comment]
I'm scratching my head as to why wildcards would not be supported out-of-the-box as a matter of course.  In all the time that CodeDeploy has been available, and all the time its predecessor project Apollo was used, this issue never came up?
